### ISSUE TITLE
Failed test GeolocationMiddleware 

### ISSUE THREAD

**Issue by Dealabs** [coopcycle/coopcycle-app#1030]
I followed all the instructions mentioned on README.md file, up  to yarn test, I get this error:
Summary of all failing tests
 FAIL  src/redux/middlewares/GeolocationMiddleware/__tests__/index.test.js (6.95 s)
  ● GeolocationMiddleware › starts background geolocation if not started

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 1
    Received number of calls: 0

      77 | 
      78 |     expect(BackgroundGeolocation.ready).toHaveBeenCalledTimes(1)
    > 79 |     expect(BackgroundGeolocation.start).toHaveBeenCalledTimes(1)
         |                                         ^
      80 | 
      81 |     const newState = store.getState()
      82 | 
![Screenshot from 2021-04-14 16-19-33](https://user-images.githubusercontent.com/69898382/114744487-45876880-9d3d-11eb-9c19-adc00a15f98e.png)

Any help to solve this issue ?
Thank you

**Comment by alexsegura** [comment]
Hi,

This test was broken in 961582e1bc6417c15e4891d8711f918ad86b6992, it needs to be updated

**Comment by alexsegura** [comment]
Fixed in 48587851503380a5798d0c0a662bd19de7b13d69
