### ISSUE TITLE
button to go online and offline does not work (app)

### ISSUE THREAD

**Issue by Carlitofastandcurious** [coopcycle/coopcycle-app#1054]
As a restaurant owner on the coopcycle application (phone and tablet), the button to go online and offline does not work. when I check on a computer, another tablet or a phone the status of the restaurant has not changed, either still online or always offline.

https://user-images.githubusercontent.com/83431363/116622947-c9e50880-a945-11eb-950b-7f71a3453677.mp4

**Comment by ERAMANrepartos** [comment]
@alexsegura is this still true? As far I know it is currently functional. I am going to close, but if you know this to still be an issue please reopen.
