### ISSUE TITLE
Implement live updates on order tracking screen

### ISSUE THREAD

**Issue by Carlitofastandcurious** [coopcycle/coopcycle-app#1055]
To be able to develop the order tracking part for the customer on the app because the page remains frozen at "the restaurant must validate your order".
![partie client](https://user-images.githubusercontent.com/83431363/116624207-d23e4300-a947-11eb-8f20-1e2ce8791770.jpg)

**Comment by alexsegura** [comment]
![cent_app_order](https://user-images.githubusercontent.com/1162230/128336588-01388331-0dd6-43a3-9b8a-e3663cee1e91.gif)
