### ISSUE TITLE
Add to the customer the possibility of seeing the name / nickname of the delivery man for more proximity and to set up marketing campaigns.

### ISSUE THREAD

**Issue by Carlitofastandcurious** [coopcycle/coopcycle-app#1062]
Add to the customer the possibility of seeing the name / nickname of the delivery man for more proximity and to set up marketing campaigns.

**Comment by ERAMANrepartos** [comment]
This is a large political decision that so far we have not made a new decision about, and until the collective decides that we want to allow for that type of closeness, with its associated risks, I am going to close the issue.
