### ISSUE TITLE
 When you want to limit a minimum number of options, this is not possible. A 3-meat tacos should have at least 3.

### ISSUE THREAD

**Issue by Carlitofastandcurious** [coopcycle/coopcycle-app#1068]
When you want to limit a minimum number of options, this is not possible. A 3-meat tacos should have at least 3.

https://user-images.githubusercontent.com/83431363/116799437-98ad3980-aaf9-11eb-9fbf-20b84f1bfb94.mp4

**Comment by vladimir-8** [comment]
Seems to be duplicated here: https://github.com/coopcycle/coopcycle-app/issues/1080
