### ISSUE TITLE
When a customer wanted to insert his promo code, there was a display bug.

### ISSUE THREAD

**Issue by Carlitofastandcurious** [coopcycle/coopcycle-app#1069]
When a customer wanted to insert his promo code, there was a display bug.

![bug affichage code promo client](https://user-images.githubusercontent.com/83431363/116799467-ede94b00-aaf9-11eb-8d8a-17bf88164c23.jpg)

**Comment by ERAMANrepartos** [comment]
Without more information about the type of device, this is not something we can do much about. Generally, we are aware of many UI bugs of this nature but have not been able to dedicate the necessary time to it. I am going to close, but the UI issue is being dealt with in the roadmap in a few different places.
