### ISSUE TITLE
Introduce "pull-to-refresh" on task list

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-app#107]
See [FlatList](https://facebook.github.io/react-native/docs/flatlist.html#onrefresh)

**Comment by alexsegura** [comment]
There is an issue on Android. 

Pull-to-refresh doesn't work, at least in the emulator. 
I think looks like you can't scroll a FlatList that doesn't overflow the screen. 

Tried a bunch of options, with no luck.

**Comment by Atala** [comment]
Does it work in iOS simulator ? Do you want me to try on a real device?

**Comment by alexsegura** [comment]
There is no need to introduce a new dependency, as this is supported by `FlatList`. 
What happens on the current version when you pull the list on a real device?

**Comment by Atala** [comment]
What should happen? Where is your commit with pull-to-refresh?
