### ISSUE TITLE
For the restaurants part, add a "ready" button when the order has been prepared earlier than expected.

### ISSUE THREAD

**Issue by Carlitofastandcurious** [coopcycle/coopcycle-app#1070]
For the restaurants part, add a "ready" button when the order has been prepared earlier than expected.

**Comment by ERAMANrepartos** [comment]
This would be a significant upgrade. We do need to spend some real time trying to identify the best way to communicate this information (notification, filter, tag, new category of on the dashboard...)

**Comment by Paul-Eraman-CoopCycle** [comment]
This will be implemented in https://github.com/coopcycle/coopcycle/issues/13 which makes this a repeat issue (with the exception that it will only work for restaurants in which it is activated)
