### ISSUE TITLE
As a customer, to be able to enter their expiration date and CVCs when scanning their credit card. Most of the time it doesn't work.

### ISSUE THREAD

**Issue by Carlitofastandcurious** [coopcycle/coopcycle-app#1074]
As a customer, to be able to enter their expiration date and CVCs when scanning their credit card. Most of the time it doesn't work.

**Comment by ERAMANrepartos** [comment]
@alexsegura Do you know what this is about? I'm not sure what "scanning" means in this context, because in our case we can input the CVC and expiration date when inputting card information.
