### ISSUE TITLE
Add the possibility for the customer to sign on task success

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-app#109]
Would that lib fit : https://github.com/RepairShopr/react-native-signature-capture ?

What should we do with captured signature (stored as base64 strings)?

**Comment by PasLoin** [comment]
Be able to print a proof of delivery from the dashboad with task detail, timestamp, name of customer, geoloc, and the captured signature.

**Comment by alexsegura** [comment]
Fixed in e79524009e44e49c1a3545dbf3bacfdf952710e7
