### ISSUE TITLE
Full address with floor and hand cannot be introduced

### ISSUE THREAD

**Issue by xabier** [coopcycle/coopcycle-app#1093]
**Describe the bug**
This is a usability but rather than a technical one, but makes it very confusing to use the app for reasons I will describe below.
When the app demands that you insert your address it only accepts the address up to the street number, if you try to introduce the floor and hand (or other details) it won't work. This is first relatively understandable because the app only needs to know if you are within range of certain restaurants, but the user doesn't know that. It is worst when you make the order. You are moven to more and more screens, including again the same adress system, and you are made to pay, but you keep with the deep uncertainty that there was no option to include your full address anywhere. Few people is willing to pay if the order might end up delivered to any of the 56 flats of your building. I finllay managed to include this additional information at the very end of the forms in a box that is not meant to add floor and hand but to include additional information for the delivery.

**To Reproduce**
1. Open the app
2. Introduce your address

**Expected behavior**
If the address needed only requires the street name, or street name and number, then I expect this to me explicitly mentioned.
I expect an additional box on the step where you need to include your address where the app asks about floor and hand.

**Smartphone (please complete the following information):**
CycleCoop App on Android

**PD** : Great job with this app and the whole project, BTW. Willing to help improve it. Thanks for this amazin job!

**Comment by ERAMANrepartos** [comment]
I understand that this is fixed. @alexsegura can you confirm this, and if i am wrong, reopen?
