### ISSUE TITLE
AddressPicker : propose addresses only located in instance country

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-app#11]

**Comment by alexsegura** [comment]
It _should_ work, geocoding queries are filtered by region 
But it doesn't work 😐

https://github.com/coopcycle/coopcycle-app/blob/378853f807ba63e68bea9ef7e7e4f36362e0890c/src/components/AddressTypeahead.js#L74

**Comment by alexsegura** [comment]
Fixed in 97e1d660576685371214d45d2eb240d57f0f585b
