### ISSUE TITLE
[UI] Tags screen issues with Radio button and selecting a tag.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-app#1114]
1. Clicking on the `radio button` of a tag DOES NOT select the tag.
2. Clicking on the name of the tag, it DOES select the tag.
3. Once a tag is select, go back to main screen
4. Go back to Hide tasks tagged with
5. Click on the name of the tag, it gets Unselected but the Radio button disappears. 
6. It's still selectable, but confusing.
![appTagsIssues](https://user-images.githubusercontent.com/51931067/121976167-262bac80-cd7b-11eb-8ea2-d5d2a5dec733.gif)

**Comment by alexsegura** [comment]
Fixed in eb026e60193960c6888df5bcfbf8913abfc718d4

We're not using radio buttons anymore, the whole list item is clickable
