### ISSUE TITLE
Date picker doesn't close by itself when opened without having selecting date.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-app#1115]
1. Open the date picker as a courier.
2. Don't select a date
3. Click anywhere else in the app, navigate the app
4. Come back to the main screen where the date picker is
5. The date picker is still open.
6. Should have closed by itself if no date was select and the user navigated somewhere else.

**Comment by Paul-Eraman-CoopCycle** [comment]
i think this is fixed now, closing
