### ISSUE TITLE
Implement "Go To Today" button in the date picker

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-app#1118]

**Comment by alexsegura** [comment]
Which date picker?

**Comment by ERAMANrepartos** [comment]
All of them

**Comment by vladimir-8** [comment]
Let me pick it up. I'm thinking of using the same layout, as it's used on the website:  ![Screenshot 2023-09-05 at 16 20 14](https://github.com/coopcycle/coopcycle-app/assets/70273239/376b1d64-9c43-443d-821d-0e9d86734689)

**Comment by Paul-Eraman-CoopCycle** [comment]
Things to fix:

- [ ] button only appears when it is not today
- [ ] button does not cover first task for couriers
- [ ] Can we change the language to "Go to Today" from "Today"?

**Comment by vladimir-8** [comment]
Fixed in https://github.com/coopcycle/coopcycle-app/pull/1641:

- [x] button does not cover first task for couriers
- [x] Can we change the language to "Go to Today" from "Today"? 

> - [ ] button only appears when it is not today

It's not as easy as it sound, I'm leaving it out for now

**Comment by vladimir-8** [comment]
Re-opening it. Found another case, that is not covered. Will be fixed in https://github.com/coopcycle/coopcycle-app/pull/1673
