### ISSUE TITLE
Optimize rendering on tablets

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-app#112]
Rendering on tablets is ugly, we need to manage scaling better. 

- https://medium.com/react-native-training/scaling-react-native-apps-for-tablets-211de8399cf1
- https://blog.solutotlv.com/size-matters/
- https://github.com/nirsky/react-native-size-matters

**Comment by eliascodes** [comment]
I'm not really sure how far to go with this at the moment.

I also found [react-native-extended-stylesheet](https://github.com/vitalets/react-native-extended-stylesheet) which looks a little more popular and looks like it solves a similar problem.

However, it's not clear to me yet how that would integrate with the `native-base` theme we're currently using.

I think for now I'm just going to use the `size-matters` methods to modify the values exported by the `native-base` theme we're using and post some screenshots of how that looks.

Then you guys can decide whether a solution like that might work or whether something more fundamental is required.

**Comment by eliascodes** [comment]
So I've put some screen shots up [here](https://github.com/coopcycle/coopcycle-app/blob/tablet-styling/docs/scaling.md) after using `react-native-size-matters` to scale the `material` stylesheet exported by `native-base` and any manually styled elements that I could find (check the diff [here](https://github.com/coopcycle/coopcycle-app/compare/master...tablet-styling)). 

The difference looks marginal, to be honest, but it has made the font a little smaller.

Do you have any specific idea of what you want it to look like on tablet?

**Comment by alexsegura** [comment]
Yes, I don't really see any difference ☹️

Nope, we don't have any specific idea for tablets... I suppose we may display more things on tablets on certain screens, that will most probably be used on tablets (for example, the restaurant screen). 

I don't know, it's a whole subject by itself and needs a lot more research... 
Right now screens are not based on any design and are moving a lot, so maybe we shouldn't take too much decisions too early? What do you think @eliascodes?
