### ISSUE TITLE
[TAGS PRODUCTS] Background colour for dietary req. and allergens on products needs more contrast

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-app#1122]
These colours make it difficult to read the dietary requirements and allergens 
![image](https://user-images.githubusercontent.com/51931067/122597416-38e7ff00-d063-11eb-9193-11de4d124337.png)

**Comment by alexsegura** [comment]
Fixed in 9527d5bdbe4414bd90ee6efd1042918dd0528c9d
