### ISSUE TITLE
[COLLECTION] Learn more popup stay stuck, can't go back, can't continue with my order

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-app#1125]
See gif.
Popup should have a **close** button., see screenshot below
![appCollectionLearnMoreCantGoBack](https://user-images.githubusercontent.com/51931067/122666401-dac33500-d1a4-11eb-9c9c-daea4ee0735b.gif)

 ![image](https://user-images.githubusercontent.com/51931067/122666406-e1ea4300-d1a4-11eb-8411-4d4f56899d68.png)

**Comment by AdrienSICKLO** [comment]
I think you need to swipe it to the top, but definitely something that needs changing.
