### ISSUE TITLE
[UI] Repeated icon in Resto settings

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-app#1130]
The calendar icon is repeated three times for 3 different settings.

1 → Keep the calendar icon
2 → Change the icon to `<i class="fas fa-utensils"></i>`
3 → Change the icon to `<i class="fas fa-store"></i>`

![image](https://user-images.githubusercontent.com/51931067/123079758-23345a00-d414-11eb-83f4-70546b14b9c3.png)

**Comment by alexsegura** [comment]
In the end I used the `list` icon to switch menus, to be aligned with the web. 
To change restaurant, I used the `refresh` icon, I couldn't find a `store` icon on FontAwesome (?)

<img width="496" alt="Capture d’écran 2021-09-16 à 09 49 33" src="https://user-images.githubusercontent.com/1162230/133572322-dafbde25-2686-440c-a958-e137a6275825.png">
