### ISSUE TITLE
Use restaurant commercial address instead of company's head office address in tasks

### ISSUE THREAD

**Issue by biologeek** [coopcycle/coopcycle-app#1133]
**Describe the bug**

**To Reproduce**
1. Create a restaurant called Bagel Zée with a commercial address and a head office address
2. Put an order and validate it
3. In courier app, pickup task shows the address of the head office instead of restaurant address

**Expected behavior**
Bagel Zée has 2 different addresses for the official head office and the restaurant. When we received orders, we noticed that in courier app as well as on the website, tasks are to pick up at home office address while it should be at commercial address.

**Screenshots**
![Screenshot_20210629152032](https://user-images.githubusercontent.com/11749973/123804840-d823b680-d8ed-11eb-9cba-3b244402205d.png)

--

![Screenshot from 2021-06-29 15-22-59](https://user-images.githubusercontent.com/11749973/123804913-ed98e080-d8ed-11eb-9775-23ccceceb86f.png)

--

![Screenshot from 2021-06-29 15-23-36](https://user-images.githubusercontent.com/11749973/123805266-38b2f380-d8ee-11eb-8b4c-321b3b8b267b.png)

**Desktop (please complete the following information):**
 - OS: *
 - Browser *

**Smartphone (please complete the following information):**
 - Device: 
 - OS: Android 9
 - Browser *

**Additional context**
Linked to issue [#2579](https://github.com/coopcycle/coopcycle-web/issues/2579) in coopcycle-web

**Comment by alexsegura** [comment]
This won't be fixed this way, see https://github.com/coopcycle/coopcycle-web/issues/2579#issuecomment-959539557
