### ISSUE TITLE
As a store owner, multiple problems when creating a delivery/order

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-app#1137]
**Expected behaviour**

As a store owner, when the settings are enabled, I should : 
-Be asked to give the weight
-Be asked to give the number of packages
-Be told the price of the job I ask for
And it should create an order.

What happens:
See as below
![Screenshot_2021-07-08-14-16-21-159_fr coopcycle](https://user-images.githubusercontent.com/59842043/124920465-a00c2a00-dff7-11eb-8db1-fcae92474226.jpg)

When clicking on "Valider", the request goes through, without asking me more information, withtout giving me a price.
And as an admin, I don't see this as an order as it should have but as a delivery. 
If I do the same process through the browser, it creates an order I have in the list of orders.

**Comment by vladimir-8** [comment]
As I understand, the browser and the app are using different ways to create deliveries (and orders)

on the browser: 
- for deliveries made by an admin/store the order is created if "Create order" setting is enabled
- for External display the order is always created

in the app: 
create delivery api is used (POST /api/deliveries), which creates only a delivery object

It seems to me that these two ways need to be combined and create delivery api should perform the same actions as are performed in the browser now

**Comment by ERAMANrepartos** [comment]
This also has created the situation where the app store orders arent registered in the excel. @lucasferraro I think this may be related to your current sprint

**Comment by Paul-Eraman-CoopCycle** [comment]
working on it in other issues, closing
