### ISSUE TITLE
Information on website that don't appear on app

### ISSUE THREAD

**Issue by shikaruko** [coopcycle/coopcycle-app#1166]
**Describe the bug**
I am an user on Sicklo and they are on holliday. We have a message about it on the website. On the app, we just have no list of restaurant.

**To Reproduce**

**Expected behavior**

**Screenshots**
![holliday website](https://user-images.githubusercontent.com/13643289/128410348-97204f11-000e-46b8-a6df-ae00528ba649.png)
![Coopcyle App sicklo](https://user-images.githubusercontent.com/13643289/128410393-cbf4a59f-0b0c-4f25-9fb5-b0a5a8be2695.png)

**Desktop (please complete the following information):**
 - OS: Linux 
 - Browser Firefox

**Smartphone (please complete the following information):**
 - Device: Cat s41
 - OS: Android 8.0
 - Browser Coopcycle App

**Additional context**

**Comment by r0xsh** [comment]
Fixed by https://github.com/coopcycle/coopcycle-app/commit/b5540433f1256ac09892818b02df52872c2c01b0
