### ISSUE TITLE
[UX] Order status on app is vague; says "accepted" while on web it shows as picked up and en route.

### ISSUE THREAD

**Issue by fabianhjr** [coopcycle/coopcycle-app#1183]
![Screenshot_20210820-151848_CoopCycle](https://user-images.githubusercontent.com/303897/130289242-c06ec36f-f30a-4816-88f6-5a844e7a6914.jpg)
![image](https://user-images.githubusercontent.com/303897/130289163-974d4376-71da-4612-91a2-685b3faa3c08.png)

**Comment by r0xsh** [comment]
Fixed by https://github.com/coopcycle/coopcycle-app/commit/7ae10ee521551f02d31ff612668c72efee8e892c
