### ISSUE TITLE
The app goes blank randomly

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-app#1259]
**Describe the bug**
Without a known pattern, the app will randomly go blank, with the uppermost red bar visible but only white below, with a rotating "in process" icon. The only way to leave the error is to close the app and reopen, but there is no way to successfully order food since the same thing happens again.

**To Reproduce**
Unknown. Seems to be random, but possibly related to when the client is doing something in the app, locks the phone, then opens the phone again to continue. We DO know it happen when opening restaurants in the app to CERTAIN phones in a predictable way. 

**Expected behavior**
That this doesnt happen...

**Screenshots**
Added

**Desktop (please complete the following information):**
 

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy 20 pro note ERROR HAPPENS
 Apple iphone 7, version 14.8.1 DOES NOT HAPPEN
Aquaris U Plus verions 7.1.1 DOES NOT HAPPEN
LG K10 4G version 6.0 DOES NOT HAPPEN

**Additional context**
This gets worse given the next error I am about to upload. will explain there.

**Comment by vladimir-8** [comment]
@Paul-Eraman-CoopCycle do you know if it occurred recently? Otherwise let's close this issue and reopen it if it happens again

**Comment by Paul-Eraman-CoopCycle** [comment]
I havent heard about it in a while but ive been less in touch with final consumers. Can close and keep an eye out yea

**Comment by vladimir-8** [comment]
Just being realistic, with the current amount of items to work on, we will probably never reach this one. Maybe it's not even an issue any more... if it is, we will hear about it again, and we will re-open it
