### ISSUE TITLE
Redesign credit card screen

### ISSUE THREAD

**Issue by AmelieA** [coopcycle/coopcycle-app#126]
here are some commun way big company do it compare to us : 
![41980190_973869066153975_6330619590569099264_n](https://user-images.githubusercontent.com/5854745/45748047-e524fe80-bc07-11e8-83de-b116b02f36be.jpg)
![f2ffcbb0-3184-486d-a391-ee1d2872b9f7](https://user-images.githubusercontent.com/5854745/45748111-130a4300-bc08-11e8-9bde-87b9150e622a.jpeg)
![2b120441-9c21-48be-a6f8-59db4bd9258b](https://user-images.githubusercontent.com/5854745/45748112-130a4300-bc08-11e8-8609-e6ccdaf2cd2a.jpeg)
![7ef5bbcb-15ea-45cc-ad19-2a37750d9fde](https://user-images.githubusercontent.com/5854745/45748113-13a2d980-bc08-11e8-97d5-86afc56ff5b2.jpeg)

**Comment by ERAMANrepartos** [comment]
It has been changes! 🥳
