### ISSUE TITLE
App goes blank at moment of payment

### ISSUE THREAD

**Issue by ERAMANrepartos** [coopcycle/coopcycle-app#1260]
**Describe the bug**

#1259

Exactly like issue #1259, but happens at payment page in the app after having created the order

**To Reproduce**
Same as #1259

**Expected behavior**
To pay normally

**Screenshots**
see #1259

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Same as 2913

**Additional context**

**Comment by alexsegura** [comment]
Should be fixed by #1251
