### ISSUE TITLE
No back button on order screen 

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-app#1262]
It is possible to land on the order screen without being able to navigate outside of it. 

To reproduce it : 
- Launch the app, logged in as a customer. 
- DO NOT navigate to the account stack (= do not click on the hamburger menu).
- Order something. 
- You land on the order "confirmation" screen, and there is no back button on the top left (i.e the button circled in blue in the screenshot below is absent).

<img width="387" alt="Capture d’écran 2021-12-09 à 16 19 34" src="https://user-images.githubusercontent.com/1162230/145424457-4ab02577-ecf6-40a3-bd75-43c2c581e137.png">

**Comment by ERAMANrepartos** [comment]
Has this been reported in the wild?
