### ISSUE TITLE
Improve management of multiple instances in the same city

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-app#1295]
Currently, as we display city names to the customer, when there are multiple co-ops in the same city, we display "City - Name of co-op", which can be confusing when there is a lot (like in Mexico City). 

Instead, at least we should display the city name, and open a popup to choose the co-op. 

A better implementation would be to allow switching between co-ops in the same city. 
It could be implemented by parsing the `coopcycle.json` data, grouping co-ops by the same city name, and then displaying "tabs" on the restaurant list screen. Clicking on each tab would load the restaurant list of each co-op, and customers would be able to navigate this way. At some point, when clicking on a restaurant for example, the app should connect to the instance under the hood, to keep the current behavior. 

---

![Tabs](https://user-images.githubusercontent.com/1162230/149836813-dafc56e8-6655-4601-820c-d00f9c92982f.PNG)

**Comment by AdrienSICKLO** [comment]
Keep in mind making it random to appear as "first tab co-op"
