### ISSUE TITLE
app crashing at ordering

### ISSUE THREAD

**Issue by AmelieA** [coopcycle/coopcycle-app#132]
Juste after putting your credit card information, the app crashes. But the order is put and can be validated like usual if it crashes. Kevin's samsung dit that. My xiami is stucked in a endless loop of charging

**Comment by AmelieA** [comment]
Correction, if you mess up your credit card infos, you've got an infinite charging loop. If you do not, it crashes and the order is made

**Comment by alexsegura** [comment]
Ok thank you for reporting that.

This is linked with cart clearing after the checkout succeeds. 

<img width="356" alt="capture d ecran 2018-09-22 a 15 59 11" src="https://user-images.githubusercontent.com/1162230/45918011-7b635980-be80-11e8-8ed2-d2340f07fce7.png">
