### ISSUE TITLE
Inline error messages are needed on mobile user are failing to complete this account subscriprion

### ISSUE THREAD

**Issue by vaudourv** [coopcycle/coopcycle-app#1342]
In order to reduce the problem faced by the users at the account creation phase
We need errors message to be added - especially for mobile users - during the account creation phase & checkout phase

As as user to complete the account creation error messages are needed
At the very least we need the following errors message to be triggered and translated in French
- uncomplete fields (mandatory fields missing) - Suggested text : "L'ensemble des champs ne sont pas remplis"
- The user doesn't enter a username - Suggested text "Merci de remplir le champs username"
- The username is invalid - Suggested text "Le format du mot du username est invalide"
-  The password is invalid - Suggested text : " Le format du mot de passe est invalide"
- The passwords don't match - Suggested text : " Les mots de passe ne sont pas identiques "
 - The email is invalid - Suggested text : " Le format de l'email est invalide"

I want these above new errors messages to be added
Using inline message while inserting their data (name, surname, email)

Current situation
A single error messages is being displayed on the mobile resulting in failed account creation or high bounce rate on mobile
currently text for account creation is
"Utilisateur et/ou mot de passe inexistant"

**Additional context**
Similar error message needed to be addede on the webapp
![Screenshot_20220215-123949 4896](https://user-images.githubusercontent.com/9380173/154055438-5a6dd5dc-1bd3-4843-913c-bc73a82f7cd2.jpg)

**Comment by Paul-Eraman-CoopCycle** [comment]
@alexsegura was this done by our most recent update?

**Comment by alexsegura** [comment]
@Paul-Eraman-CoopCycle no, it needs to be reported in the app.

**Comment by Paul-Eraman-CoopCycle** [comment]
So finished on web, not on app?

**Comment by vladimir-8** [comment]
Added messages to the login flow:

Fields validation:

![Simulator Screenshot - iPhone SE (3rd generation) - 2023-12-21 at 16 38 08](https://github.com/coopcycle/coopcycle-app/assets/70273239/e4d94515-122a-4996-a447-4d234183996b)

Wrong credentials:

![Simulator Screenshot - iPhone SE (3rd generation) - 2023-12-21 at 16 38 24](https://github.com/coopcycle/coopcycle-app/assets/70273239/b35612d5-d45f-48b2-8bea-6b946b236277)

In the registration flow, we actually have these messages already implemented:

![Simulator Screenshot - iPhone SE (3rd generation) - 2023-12-21 at 16 38 35](https://github.com/coopcycle/coopcycle-app/assets/70273239/042eea56-df60-4dea-b469-94461c58b50b)

Let me know if anything else is expected in scope of this issue

**Comment by vladimir-8** [comment]
Fixed in https://github.com/coopcycle/coopcycle-app/pull/1657
