### ISSUE TITLE
Recurrent rules not generating the name of the store in the tasks in the App.

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-app#1376]
When using the recurrent rules the tasks created in the App don't show the name of the store they are attached to. Can be confusing for a courier who doesn't know the client.

See attachment
![screenshot_2022-04-26-14-48-15-47_534fb49acdec2e02cecedad82e231bfd](https://user-images.githubusercontent.com/59842043/165334781-d54a489e-29d2-4fb4-ad49-76030e1139d7.jpg)
t

**Comment by alexsegura** [comment]
Maybe the best solution is to display the `task.orgName` in `TaskListItem`

https://github.com/coopcycle/coopcycle-app/blob/0f532eff5b9ba47ebd4ec0279ea0be87e6e70b70/src/components/TaskListItem.js#L182-L183

Pretty much like how it's done on the dashboard:

https://github.com/coopcycle/coopcycle-web/blob/bf3fba703c2af9612a82988cd4a47b962d4c5472/js/app/dashboard/components/Task.js#L18-L44
