### ISSUE TITLE
Use Fastlane at full potential

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-app#1404]
We now want to be able to deploy custom apps for co-ops (with their own branding, etc). 
It seems to be possible to do most of the painful job using Fastlane. 

- [ ] Set release notes / changelog (seems possible using Fastlane metadata, see fastlane/fastlane#13851)
- [ ] Use Fastlane to configure Google Play entirely (see https://github.com/fastlane/examples/blob/master/SunApps/Deliverfile)

**Comment by alexsegura** [comment]
https://blog.swmansion.com/build-and-publish-multiple-rn-apps-from-the-same-codebase-29bf3bc54f7f

**Comment by r0xsh** [comment]
[Easily sync your certificates and profiles across your team](https://docs.fastlane.tools/actions/match/)

**Comment by Paul-Eraman-CoopCycle** [comment]
Apparently we are at 70%! and given we are using the 80/20 rule, good for the moment! 🥳
