### ISSUE TITLE
In order to avoid mishaps As a [courrier] I want [more space between the validation and POD buttons]

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-app#1449]
**In order to**  avoid on the validation button by mistake

**As a** courrier

**I want**more space left between the 'proof of delivery' and the 'validation' buttons

**Whereas currently** they're right above each other and there's a lot of unused space on that screen so the POD could be a little higher so the courriers don't click by mistake with their sometimes big fingers (especially with gloves in the cold weather)

**Additional context**
see screenshot
![photo1666686585](https://user-images.githubusercontent.com/44605344/197724306-a0c6e83a-ebc3-4e70-bda5-55f8b7af69bd.jpeg)

**Comment by Paul-Eraman-CoopCycle** [comment]
Not planned currently
