### ISSUE TITLE
Store onboarding text/images on official website

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-app#1465]
Currently it's stored in the `CustomOnboarding` screen, but it should definitely be stored online. 

https://github.com/coopcycle/coopcycle-app/blob/52eb1a0d55d4b8c7779d905d1194d169e66ef752/src/navigation/home/CustomOnboarding.js#L9-L24

**Comment by Paul-Eraman-CoopCycle** [comment]
disabled code, not planned
