### ISSUE TITLE
Difficulties to choose "click-and-collect" option

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-app#1470]
**Describe the bug**
When I click on the "Click & collect" button, the selection remains stuck on "Delivery". I have to click on "as soon as possible" to active the "Click & collect" selection.

**To Reproduce**
1. Go to Vagabond Restaurant (with the app, not in a browser)
2. Choose a product and click on command
3. try to select "Click & collect"

**Expected behavior**
- selction right option on a click
- display option selected before come back on the previous page

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Samsung XCOVER Pro] SM-G715FN/DS
 - OS: [Android 13 - ONE UI 5.0]
- app 2.5.1

https://user-images.githubusercontent.com/44605344/213455331-be85496b-d4e1-4b1e-b216-a09f944c9306.mp4

**Comment by alexsegura** [comment]
@ERAMANrepartos this is the problem we saw in Vitoria-Gasteiz
