### ISSUE TITLE
As a flying dispatcher/courier, I want to select multiple tasks in an easier way to save time

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-app#1476]
Right now, as a courier or a dispatcher, I can only select one task at a time before choosing what to do with it.

With the multiplication of routes with large numbers of points, I would need to be able to handle quicker this important number of tasks.

1- As a courier, having the possibility to select multiple pick ups at same location and finishing these tasks in one go would save a lot of time.

2-As a flying dispatcher, I could select multiple tasks and assign them to a courier directly without having to do it one by one.

I found this model on another solution. Maybe checkboxes is another option

![image](https://user-images.githubusercontent.com/59842043/217774575-6d481940-7c43-42fa-921f-9d51c5fa3d97.png)

**Comment by alexsegura** [comment]
We could also use long press to select multiple tasks + show a [Fab](https://docs.nativebase.io/fab) to trigger the complete action.
