### ISSUE TITLE
Remaining tour distance for couriers

### ISSUE THREAD

**Issue by Adrien-Narvelos** [coopcycle/coopcycle-app#1477]
**In order to**  improve battery charge management

**As a** courier

**I want** tour remaining distance to be prompted on app

**Whereas currently** this data is not available

**Comment by alexsegura** [comment]
@Adrien-Narvelos I'm not sure to understand what you want? And I don't understand the relationship with battery? 
Can you add more context please?

**Comment by alexsegura** [comment]
May be linked with coopcycle/coopcycle-web#1203

**Comment by Adrien-Narvelos** [comment]
> May be linked with [coopcycle/coopcycle-web#1203](https://github.com/coopcycle/coopcycle-web/issues/1203)

Not really

**Comment by Adrien-Narvelos** [comment]
> @Adrien-Narvelos I'm not sure to understand what you want? And I don't understand the relationship with battery? Can you add more context please?

As a courrier I want to know how much distance I still have to cover in my tour, so that I can manage battery sollicitiation and avoid emptying the battery before the end (or warn dispatch that I will not be able to do the whole tour)

**Comment by ERAMANrepartos** [comment]
This is a feature that cannot be part of the coopcycle app, it must be done on a rider level
