### ISSUE TITLE
In order to reduce the number of incorrect addresses, as a B2C foodtech client I want to be asked if this address is correct in a map format

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-app#1495]
**In order to**  `achieve something`
Reduce how many incorrect addresses we get due to incorrect geolocation or picking the wrong thing on the dropdown list

**I want** `something to be added or changed`
Confirm the address with the customer after they input it by overlaying the point that is geolocated on the map and asking if this is correct. Maybe this should not happen immediately in order to facilitate the purchasing path, maybe at the end in review, but if it could happen in an unobtrusive way it could avoid a lot of problems.
If the point is the the wrong place, you could move the point to a new location on the map (probable moving the map while the point remains centered) that changes the lat-long of the point, but not the written delivery information. 

**Whereas currently** `this happens`
It never confirms the address, and often we get incorrectly placed points on the map.

**Comment by vladimir-8** [comment]
Duplicates https://github.com/coopcycle/coopcycle-app/issues/1512 ?

**Comment by Paul-Eraman-CoopCycle** [comment]
Yes, good catch. Closing
