### ISSUE TITLE
In order to avoid accidentally changing the date, as a a courier I want the date function to change

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-app#1498]
**In order to**  `achieve something`
A clear description of a goal you want to archive

**As a** `role`
Who would benefit from this change, e.g. a dispatcher, a courier, a restaurant ...

**I want** `something to be added or changed`
1. the arrows that change the date from one day to another be eliminated, and a calendar selection modal be put in settings.

![image](https://github.com/coopcycle/coopcycle-app/assets/77277854/e5948c55-5688-49d7-b3b8-c423de808b78)

2. The date be change to be "Today" vs "DD/MM/YYYY" instead of "DD/MM/YYYY"

![image](https://github.com/coopcycle/coopcycle-app/assets/77277854/abd85142-f35d-4850-98e6-baed9ecc7d00)
![image](https://github.com/coopcycle/coopcycle-app/assets/77277854/6d95e05c-7de7-49bf-8a14-78b87d89d9c6)

**Whereas currently** `this happens`
Because the date format never changes, there is no visual cue that you are on the correct day. 
And because the arrows are near the settings button and the menu button, it is easy to accidentally change days without meaning to or without noticing.

**Comment by vladimir-8** [comment]
If the selected date is not Today; show Go to Today button on both list and map
