### ISSUE TITLE
App crashes when trying to edit delivery time or switch to click and collect

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-app#1505]
**Describe the bug**
When I click "edit" on the delivery time, or once having arrived in the edit page, if I click on "collect" on the upper right, the app crashes. 

**To Reproduce**
1. To a restaurant and select a few items
2. Click on "order"
3. Click on "edit" of the delivery time
4. App crashes

**Expected behavior**
Not crashing

**Screenshots**

https://github.com/coopcycle/coopcycle-app/assets/77277854/8520e8b1-8adb-4fc0-afe4-db37a3c22156

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device:  iPhone5
 - OS: iOS app

**Additional context**

**Comment by r0xsh** [comment]
May be fixed with: [#1443](https://github.com/coopcycle/coopcycle-app/pull/1443)
