### ISSUE TITLE
In order to simplify orders handling As a restaurant I want a better notification system

### ISSUE THREAD

**Issue by r0xsh** [coopcycle/coopcycle-app#1508]
- No blocking UI
- Dont stack notfications when multiple orders arrives
- Better indicate if an order is a pre-order

**Comment by vladimir-8** [comment]
Duplicates https://github.com/coopcycle/coopcycle-app/issues/1513 ?

**Comment by Paul-Eraman-CoopCycle** [comment]
im going to make an epic for this. closing this issue for now, but itll be in the discovery section
