### ISSUE TITLE
In order to avoid not seeing customers comments as a courier and dispatcher I want a flag to alert me to a comment in the task

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-app#1510]
In order to achieve something
Become aware of possible issues before they become an issue...

As a role
Person who sees tasks in the app - mobile app dispatcher or bike courier who is looking at tasks in the application

1. Courier app map
![image](https://github.com/coopcycle/coopcycle-app/assets/77277854/26ce97f8-2b6e-456a-8c5f-c4df3caca8a8)

2. Courier app list
![image](https://github.com/coopcycle/coopcycle-app/assets/77277854/c81688f5-7a39-4186-a896-4a293eb4c475)

3. Dispatcher app list
![image](https://github.com/coopcycle/coopcycle-app/assets/77277854/edbe40f8-31e5-485c-935c-74baa58e540c)

I want something to be added or changed
To have a "flag" that visually alerts me to the fact that an order has a comment without having to open it.

Whereas currently this happens
Because you do not know there is a comment until looking at the last possible part of the order (opening the task and scrolling all the way down), it is easy to not notice an important piece of information until it is too late (ex: don´t ring, sleeping baby!)
It might also be a good idea to make the comment "pop" more in the order details model as well

**Comment by lucasferraro** [comment]
@Paul-Eraman-CoopCycle and Yeray
It looks like this at the moment (ready for UI/UX review):

**Coureir Map view**
Show red icon at top-right corner warning that there are something important to check about task: comments, etc.
<img width="300" src="https://github.com/coopcycle/coopcycle-app/assets/4819244/a4a5928a-95ad-4fca-8d06-b4077a84acc2" />

**Coureir Map view**
Clicking on map marker the task popup shows a "comment" icon warning about that.
<img width="300" src="https://github.com/coopcycle/coopcycle-app/assets/4819244/f53fdb4e-5bf7-43ed-95ae-eda91a136ffe" />

**Coureir Map view**
Task popup looks like this when task has comments and tags.
<img width="300" src="https://github.com/coopcycle/coopcycle-app/assets/4819244/c6d7ff92-963b-4385-a47c-2546e368b794" />

**Courier List view**
In the tasks list show a "comment" icon for those tasks that have a comment attached.
<img width="300" src="https://github.com/coopcycle/coopcycle-app/assets/4819244/56cf6e3c-9367-440a-9d8e-25ebb4e5f774" />

**Dispatcher Unassigned Tasks List view**
In the tasks list show a "comment" icon for those tasks that have a comment attached.
<img width="300" src="https://github.com/coopcycle/coopcycle-app/assets/4819244/68ad4b77-935e-42ee-b093-225c84202d8a" />

**Dispatcher Assigned Tasks List view**
In the tasks list show a "comment" icon for those tasks that have a comment attached.
<img width="300" src="https://github.com/coopcycle/coopcycle-app/assets/4819244/de8b254b-93c9-4497-96fe-4f08675e6ad2" />

**Comment by lucasferraro** [comment]
For foodtech all tasks always have comments attached (the order detail with products information). So we need to show this new flag alert based on another information.
The important information that riders need to be alerted about is any instruction about the delivery.
So we need to have:
- [ ] a new field to enter information about the "floor and/or apartment"
- [ ] show the new alert flag only if user enters information in the existing field "instructions for delivery"

**Comment by Paul-Eraman-CoopCycle** [comment]
🥳
