### ISSUE TITLE
In order to allow for random deliveries, as a final consumer I want the ability to make orders without a shop interface

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-app#1511]
**In order to**  `achieve something`
The embed feature that allows individuals to request a delivery based on a series of rules predefined by the cooperative currently only exists in the web. This feature should also exist in the application. 

**As a** `role`
Final consumers

**I want** `something to be added or changed`
see above

https://eraman.coop/paqueteria/
![image](https://github.com/coopcycle/coopcycle-app/assets/77277854/b0f2f45c-2c2a-496e-b1cb-7f02f9f4ee00)

**Comment by ERAMANrepartos** [comment]
https://github.com/quiquegarcia/coopcycle-app

related unpublished branch

**Comment by Paul-Eraman-CoopCycle** [comment]
there are [forms](https://demo.coopcycle.org/admin/forms) for this
