### ISSUE TITLE
I cannot access the CDMX instance 

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-app#1516]
**Describe the bug**
I cannot access the CDMX instance because it "is down for maintenance" but it shouldnt be

**To Reproduce**
1. Go the app
2. Go to change your server in the list (click menu on the left, click person icon, click "change servers")
3. Try to enter the mexico city instance
4. See maintenance altert

**Expected behavior**
One cooperative being in maintenance mode should not stop the entire CDMX app interface from functioning

**Screenshots**
![image](https://github.com/coopcycle/coopcycle-app/assets/77277854/9d2df5fa-1603-4404-8534-702237156d76)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - mobile application

**Additional context**

**Comment by Paul-Eraman-CoopCycle** [comment]
Can we ask TWC to stop being in maintenance?

**Comment by AwesomeKuro** [comment]
I think It is just better to now allow servers in maintenace break the selection. With this change, you would have to enter the server selection screen to change cities, but nothing else changes. Cart carry over within the same city should still be working
