### ISSUE TITLE
Opening hours are incorrect

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-app#152]
> il est affiché ( chez moi et sur le site ) ouvert de lundi a vendredi de 19h a 22h ( c'est les bons horraires ) mais sur ça tablette il vois "ouvert du dimanche au dimanche de 19h a 22h"

**Comment by TifaineSicklo** [comment]
Oui et il ne peut pas accéder au planning. Possibilité aux restaurateurs de gérer leur planning et leurs horaires via leur tablette ?

**Comment by ERAMANrepartos** [comment]
My french isn´t great, but I think this is resolved.
