### ISSUE TITLE
Delivery form in app

### ISSUE THREAD

**Issue by DanielBustillos** [coopcycle/coopcycle-app#1522]
As mentioned in #3672  I would like to request the implementation of an in-app delivery request feature to enable users to place delivery deliveries ("encargos") from point A to point B within the CoopCycle app. This functionality is available through a delivery form or as a user with a store account, but it is not directly accessible from the app itself.

**In order to**  `achieve something`
The objective is to provide a more streamlined and convenient way for users to request orders through the CoopCycle app.

**As a** `role`
As a final user of the CoopCycle app.

**I want** `something to be added or changed`
I want to have a way to set up deliveries directly from the app. Currently, this can be done through a form on the homepage, but it should also be accessible within the app.

**Whereas currently** `this happens`
Currently, a form setup on the homepage allows for delivery requests, but it is not integrated into the app itself. This form has been partially implemented by @AwesomeKuro 

**Additional context**

- The form can be included through the left lateral menu
- It should be possible to set up an specific pricing for the delivery requests
- The flow of item deliveries should imitate that of popular ride-hailing services

Additional context:
This feature request has been inspired by feedback and input from various courier services in Mexico. 
@AwesomeKuro  can implement this with @alexsegura and @@Paul-Eraman-CoopCycle .

Thank you  😀.

**Comment by AwesomeKuro** [comment]
What about authentication? Can we pass a token to the url so we can use the authenticated user to the form? Or is there any other way?

**Comment by alexsegura** [comment]
@AwesomeKuro this form doesn't require authentication.

**Comment by AwesomeKuro** [comment]
Solved with
https://github.com/coopcycle/coopcycle-web/pull/3729
#1527 
This is just linking the delivery form... It just choses the first Delivery Form matching "show on homepage"
