### ISSUE TITLE
Deactivated products do not appear in the app

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-app#1526]
**Describe the bug**
When a product runs out and we deactivate the product temporarily it should appear as greyed out and not be possible to select as happens in the website. Instead, in the app it simply disappears.

**To Reproduce**

**Expected behavior**

**Comment by vladimir-8** [comment]
That should be an easy fix, let me try to do it

**Comment by Paul-Eraman-CoopCycle** [comment]
Sounds great, thank you!

**Comment by Paul-Eraman-CoopCycle** [comment]
🥳
