### ISSUE TITLE
The message to warn the customer about a closed restaurant has multiple problems

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-app#1538]
When entering a restaurant on the app that is not open yet, there's a message warning him that the restaurant is closed.
We had implemented that to avoid having people order from closed restaurants, or people expected orders earlier than possible.

![image](https://github.com/coopcycle/coopcycle-app/assets/59842043/5cae1a0a-2946-4337-9c3b-9dd29ecbcb9f)

There's a couple problems on this.

- First, the message is written twice. I checked and sometimes it's not but most of the times, it comes out twice. Didn't find a pattern.
- The second problem is the wording which doesn't make any sense. It should be a more appropriate English sentence, no capital T at "Today" and there should be a coherent cause and effect link between the first sentence and the second. Maybe, do not mention "closed" but just say "opens at that time...".

I'll let native English speakers manage this side of the solution! :)

**Comment by Kooglof067** [comment]
Hi ! 

The change is not happening on our custom app 😕

![Screenshot_20231124-145432.png](https://github.com/coopcycle/coopcycle-app/assets/74900690/5c99b0f6-6572-4a39-bbd4-01eef3db7cce)
