### ISSUE TITLE
To [see the method of payment for each order] As a [restaurant or courier] I want to [show the payment method icons]

### ISSUE THREAD

**Issue by ArtemioMarquez** [coopcycle/coopcycle-app#1542]
**For** `see the method of payment for each order`
In Mexico we accept cash payment, so the courier and the restaurant need to know what the payment method was for each delivery.

**As** `restaurant or courier`
the courier and the restaurant need to know this information without having to use the computer to properly handle the cash

**I want** `show the payment method icons`
for the courier, on the task list screen, show in each order what is his payment method and for the restaurant, on the main screen or in the order details.

**While currently** "this happens"
the restaurant has to open the web version or ask the dispatcher and the courier always has to ask the dispatcher

**Additional context**
Since we are handling cash, when the courier charges the customer, sometimes they do not have the money to settle the payment, that is, the order was $430, the customer pays with a bill of $500, if the courier does not have the $70 , is a problem, another improvement would be that the client had a field to tell us how much money he will pay with
![Imagen de WhatsApp 2023-09-07 a las 08 42 25](https://github.com/coopcycle/coopcycle-app/assets/65909776/cd7a824a-4fc8-410b-8344-e62181a6b474)
![Imagen de WhatsApp 2023-09-07 a las 08 42 251](https://github.com/coopcycle/coopcycle-app/assets/65909776/301bdb90-e0af-473d-aa13-bd2efd9131bc)
![Imagen de WhatsApp 2023-09-07 a las 08 42 252](https://github.com/coopcycle/coopcycle-app/assets/65909776/a1b7286b-d25a-4d3d-8a35-f2c114098aa3)
![issue1](https://github.com/coopcycle/coopcycle-app/assets/65909776/9d435897-f06e-4196-b9a1-6a2175e1518b)
![issues](https://github.com/coopcycle/coopcycle-app/assets/65909776/6090031c-bc9c-43dd-b06f-1bce92431314)

**Comment by lucasferraro** [comment]
Hi @ArtemioMarquez ! 
Changes for this are already pushed but you will have to wait to next release of the app to have it available.

Here you can see some images of how it would look like:

**For courier**
- task list screen -> PM icon
<img width="400" src="https://github.com/coopcycle/coopcycle-app/assets/4819244/49e11139-3891-48c4-be96-88de643b1f60" />
<img width="400" src="https://github.com/coopcycle/coopcycle-app/assets/4819244/74e4712b-7ff5-440f-b8a8-ed83b2e1de82" />

- task detail screen -> PM icon + description
<img width="400" src="https://github.com/coopcycle/coopcycle-app/assets/4819244/fe364ffb-dadd-49ec-9f00-d8c6374b2aec" />
<img width="400" src="https://github.com/coopcycle/coopcycle-app/assets/4819244/ed2e0db4-40ee-4838-a119-433606d038f4" />
 
**For restaurant**
- order list -> PM icon
<img width="400" src="https://github.com/coopcycle/coopcycle-app/assets/4819244/428d43b9-43f4-40aa-bd4f-966b677fe378" />
<img width="400" src="https://github.com/coopcycle/coopcycle-app/assets/4819244/22d9b16d-cedf-4040-ad45-9595b560eda6" />

- order detail -> PM icon + description
<img width="400" src="https://github.com/coopcycle/coopcycle-app/assets/4819244/0cafc8cf-b6d2-4891-8a1b-2c76b368b89b" />
<img width="400" src="https://github.com/coopcycle/coopcycle-app/assets/4819244/ec9e2a2a-f9ca-43a9-aef1-25a8a80ddf69" />
