### ISSUE TITLE
In order to [not miss anything] As a [courier] I want [the presence of reusable packages to be clearer]

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-app#1583]
Right now, it appears like this:

![image](https://github.com/coopcycle/coopcycle-app/assets/59842043/4e834aa6-2aa0-4292-b81e-6b9480588f69)
![image](https://github.com/coopcycle/coopcycle-app/assets/59842043/40e5cab0-3a0d-4e08-a4ac-67315e237b20)

It should probably be in bold in the task. Also, a pictogram in the list of tasks would be necessary.

**Comment by vladimir-8** [comment]
- [ ] https://github.com/coopcycle/coopcycle-app/issues/1822
- [ ] https://github.com/coopcycle/coopcycle-app/issues/1823

**Comment by alexsegura** [comment]
Duplicate of #1822
