### ISSUE TITLE
As a consumer I want to be able to choose how many reusable containers I want to give back to the courier

### ISSUE THREAD

**Issue by impec-dev** [coopcycle/coopcycle-app#1586]
**Describe the bug**
During my zero-waste order, when I select the reusable container I want to give back to the courier, I can only give back all the containers of 1 format or 0

**To Reproduce**
1. Go to a zero-waste delivery and make an order with a consumer account who has some containers at home
2. Click on "manage"
3. See there is on buttons "give back my container" even if there are several containers

**Expected behavior**
I should be able to select how many box I want to give back (if I broke one I cannot give back for example)

**Screenshots**

https://github.com/coopcycle/coopcycle-app/assets/83373118/7745ee5f-f502-40ab-9d13-2fb4d0096a2b

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alexsegura** [comment]
Fixed in 2fa29f78ff057f932b11537ade1aeafc01678ea5

Improved UI in 6c51755edcd3c52e4c4dbd69c62ce2cd6cde4a84
