### ISSUE TITLE
Slogan and Custom confirmation message don't appear on App

### ISSUE THREAD

**Issue by GuillaumeNaofood** [coopcycle/coopcycle-app#1589]
**Describe the bug**
In the browser web coopcycle, we have the Slogan and the Custom confirmation message. There is not problem.
But in the App, theses 2 informations are nowhere to be found. I don't know if it's a bug or normal. So maybe, this issue should be "a new feature", sorry about that.

**To Reproduce**
1. Launch the app
2. See on the top of the "home page", there is not Slogan.
3. Make an order, and pay.
4. Then on the confirmation steps page. See the bug, there is no Custom Confirmation Message.

**Expected behavior**
We should see the slogan on the top of the "home page".
We should see the custom confirmation message somewhere at the confirmation page, or a button to click on, maybe a pop-up button, something like that could make the deal.

**Screenshots**
2 screens to help you.

**Desktop (please complete the following information):**
- Android V10

**Smartphone (please complete the following information):**
- Smartphone OPPO A72
 
![Custom message confirmation](https://github.com/coopcycle/coopcycle-app/assets/144671333/04a602b8-e72f-4b25-aee9-521048acc0e5)
![Slogan](https://github.com/coopcycle/coopcycle-app/assets/144671333/35e76fc8-b119-464b-ab41-c5b545b81e76)

**Comment by alexsegura** [comment]
As I have no clear design, the motto/slogan now appears in the drawer menu. 

![Simulator Screen Shot - iPhone SE (3rd generation) - 2023-12-29 at 16 19 31](https://github.com/coopcycle/coopcycle-app/assets/1162230/e078b2f9-353b-46e0-932c-728d2f16d2fc)

**Comment by alexsegura** [comment]
Custom confirmation message now appears on order tracking page.

![Simulator Screen Shot - iPhone SE (3rd generation) - 2023-12-29 at 16 37 24](https://github.com/coopcycle/coopcycle-app/assets/1162230/f4d7199b-55f4-480e-997e-e5d25995928d)
