### ISSUE TITLE
Choice selection bug return top of the scroll field

### ISSUE THREAD

**Issue by GuillaumeNaofood** [coopcycle/coopcycle-app#1591]
**Describe the bug**
When you click on an option in the scrolling selection on a plate or product, it returns at the top of the scrolling field.
We shoulf also, just as Deliveroo or Uber Eats, have a whole scrolling page for the options, and not just a little scrolling field 1/3 page at the bottom.
Plus, the informations at the top of the page are not usefull for the options selection.

**To Reproduce**
1. Go to home page app and click on a restaurant
2. Then click on a product with an option selection
3. And try at the bottom of the page, the scrolling field and try to select the option at the bottom of the scrolling field.
4. And see the error, you come back at the top of the scroll selection each time.

**Expected behavior**
When we select an option, we should skip at the next choice title OR stay right where we are at the moment.
And, the whole page should scroll entirely. To be more fluid and clear.

**Screenshots**
4 screens 

**Desktop (please complete the following information):**
- Android V10

**Smartphone (please complete the following information):**
Smartphone OPPO A72

![Exemple Deli 1](https://github.com/coopcycle/coopcycle-app/assets/144671333/371d8a20-3066-4bf7-8389-e1ed2ce0d462)
![Exemple Deli 2](https://github.com/coopcycle/coopcycle-app/assets/144671333/8b1e736a-2d30-4cfe-b117-753781c56585)
![Nao scroll 1](https://github.com/coopcycle/coopcycle-app/assets/144671333/4994b09e-fcce-40e3-929a-e5cecf6874b1)
![Nao Scroll 2](https://github.com/coopcycle/coopcycle-app/assets/144671333/0335550a-be41-4219-ac6d-1e04c2ad8593)

**Comment by Paul-Eraman-CoopCycle** [comment]
https://github.com/coopcycle/coopcycle-app/assets/77277854/2bd9d52b-356c-48db-9a83-9c654d328076
