### ISSUE TITLE
In the app a rider can show a simple polyline between their tasks

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-app#1600]
<s>**In order to**  `achieve something`
- When a rider is assigned a tour, I should see the tour "line" on the map view of the tasks list. Or other vizualisation that the tasks are linked
- In the list view of the tasks list nothing is changed</s>

-> changed to "In the app a rider can show a simple polyline between their tasks"

**Comment by Paul-Eraman-CoopCycle** [comment]
This should not be when a rider is assigned a tour, it should be a setting in the configurations like the activation or deactivation of seeing finished tasks
