### ISSUE TITLE
Customers making multiple payment captures in Stripe by accident

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-app#1603]
We frequently get clients who have made 3 or 4 "payments" (authorizations of payment) in Stripe. We believe it is happening due to some UI or loading issue with the app, because they do not realize that they have done this until they look at their bank account. 

It´s bad because it creates a pretty bad relationship with the client

**Comment by vladimir-8** [comment]
Closing this issue, as it currently happens less often than it used to. If it happens again, lets look at each case individually first
