### ISSUE TITLE
 Restaurant statistics do not show STRIPE commission

### ISSUE THREAD

**Issue by ArtemioMarquez** [coopcycle/coopcycle-app#1604]
**Describe the bug**
Restaurant statistics do not show STRIPE commission. the data table presents values ​​​​at zero

**To Reproduce**
1. Go to 'Restaurants'
2. Click on 'stats'
3. See error

**Expected behavior**
This field should show the sum of FEE and taxes.

**Screenshots**
![Captura de pantalla 2023-11-13 121607](https://github.com/coopcycle/coopcycle-app/assets/65909776/74c2d656-61ac-4baf-9a8a-77d9e9be6357)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome

**Additional context**

**Comment by Paul-Eraman-CoopCycle** [comment]
🥳
