### ISSUE TITLE
Credit card details fields are unclear and can lead to abandoning cart

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-app#1606]
**Describe the bug**
Usually, when on a website to buy something, placing credit card details is done by filling in 3 different fields that are the actual number, the expiration date of the card and the CVV field.

In our case, everything is expected in one field which is super counter intuitive.

**To Reproduce**
1. Go to 'any restaurant..'
2. Click on 'products.'
3. Go to checkout

![Screenshot_2023-11-14-11-37-53-998_fr naofood client](https://github.com/coopcycle/coopcycle-app/assets/59842043/d1e56cad-fd55-4ed5-aa2c-2a47b4c30881)

**Comment by Kooglof067** [comment]
Something to add to this : I tried to use the gpay automatic filling method and it failed, but when I filled it manually it worked fine.


Sorry I didn't know how to put this but this is Valentin who write so text me if you need more explanation.

Thank you :)

**Comment by vladimir-8** [comment]
I see that the legacy `Card Element` that is currently used supports displaying card input as 3 different fields: https://stripe.com/docs/payments/payment-card-element-comparison

**Comment by vladimir-8** [comment]
After looking at it more closely, I see that `Card Element` can do it only on the web. On the mobile app, it's possible to display card input as three different fields (`CardForm`), but then it adds country and postal code fields:

![Simulator Screenshot - iPhone 15 - 2023-12-20 at 16 37 08](https://github.com/coopcycle/coopcycle-app/assets/70273239/2b91d0cf-0024-49f6-95ee-10052ea42071)

Currently, it's not possible to hide them, and I see people are asking to allow it for a few years already :( 

I found a comment which says that it's possible to hide them in the new `Payment Sheet` component, but I can not verify that without a test setup: https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet

So here are the options I see at the moment:

1. Leave it as it is until it's implemented in the stripe library
2. Switch to `CardForm` component, even if it requires us to add country and postal code
3. Switch to the `Payment Sheet` component, which maybe let us show these three fields without country and postal code. But it's the latest way to integrate that Stripe has, plus it adds support for more payment methods, including Apple and Google Pay. https://stripe.com/docs/payments/payment-element It will be a bigger effort, including changes on the backend.

What do you think? @Paul-Eraman-CoopCycle @AdrienSICKLO

**Comment by Kooglof067** [comment]
Option 3 seems to be very nice but on the other hand if it's requires less work, option 2 can be a good compromise (I guess ?)

**Comment by alexsegura** [comment]
> Switch to CardForm component, even if it requires us to add country and postal code

IMHO it would cause other problems. 
As said in the initial message, _usually_ you are not asked for your country and postal code.

**Comment by alexsegura** [comment]
I'm sorry, but this issue comes with no proof that the current credit card field leads to abandoning carts. 

How has this issue been identified? 
User testing? Phone calls from customers? How frequently is it reported?

**Comment by alexsegura** [comment]
I mean, the credit card field we are currently using is the default UI from Stripe, who has a team of designers who have been working on optimizing it. We are not the only ones using it as-is. 

It is what Stripe recommends to use, it does not have custom code (= more maintenance in the future).

I would not recommend touching any of it.

**Comment by alexsegura** [comment]
`CardForm` is considered as deprecated. 

https://github.com/stripe/stripe-ios/issues/1932#issuecomment-1868445798

**Comment by Paul-Eraman-CoopCycle** [comment]
<img width="594" alt="Screenshot 2024-01-21 at 00 43 30" src="https://github.com/coopcycle/coopcycle-app/assets/77277854/b2b7134b-ce07-432c-9560-7c907509ed0c">

Doesn't show spain or french examples on a first look, but the EUR one has paypal and bancontact, seems like even if this isnt an abandoning cart situation, the new modal has some nice improvements, no?

**Comment by AdrienSICKLO** [comment]
Hey, sorry I had missed those notifications. 
I was actually ordering myself with Marina and Remi, and it took us 30sec to realize that it was possible to order and this was not a bug.
I checked on both competitors Deliveroo and Uber and they both have the 3 fields. Like 99,9% e commerce websites in France

**Comment by Paul-Eraman-CoopCycle** [comment]
we will be implementing that other modal, so we can track in that issue (in pricing v.1), closing this as not planned
