### ISSUE TITLE
When assigned a tour in the dispatch panel the rider shall see the tasks listed in their task list in app

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-app#1608]
The tasks are shown as normal tasks, the rider doesnt know if it is part of the tour (will be improved)

**Comment by Atala** [comment]
@Paul-Eraman-CoopCycle should be good can you test on your instance and close ?

**Comment by Paul-Eraman-CoopCycle** [comment]
Don't think it's updated. Can you send me a screen cap of what it should look like?

**Comment by Atala** [comment]
It is just that the tasks from a tour are displaying correctly in the courier app
