### ISSUE TITLE
I want search results to prioritize the option that is close to the cooperative´s location

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-app#1611]
In many places street names repeat between cities, so when I search for street X i get results from many cities. Can we put the address that is closest to the cooperatives geolocation first somehow?

https://github.com/coopcycle/coopcycle-app/assets/77277854/2117c4f6-1a1b-4df8-9d2b-0df477d1b8a7

**Comment by alexsegura** [comment]
We should be using the `locationBias`/`locationRestriction` parameters from [Google Places Prediction service](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service?hl=en)

**Comment by alexsegura** [comment]
See coopcycle/coopcycle-web#3883 for implementation
