### ISSUE TITLE
Reintroduce Redesign Changes for Improved User Experience on Restaurants closure and pre-orders

### ISSUE THREAD

**Issue by r0xsh** [coopcycle/coopcycle-app#1619]
**Issue Description:**
The previous pull request https://github.com/coopcycle/coopcycle-app/pull/1443 introduced a redesign aimed at enhancing user experience, particularly in scenarios involving restaurant closure and pre-orders. However, the changes were not retained. This issue is created to reintroduce the redesign changes.

**Details:**
- Clarify and assist users in identifying when a restaurant is closed.
- Provide clear indications when a pre-order is being created.
- Implement a new timing modal.
- Warn users when the store is about to close.
- Trigger a modal when an order is converted to a pre-order, prompting the user for further actions.

**Context:**
In the current app, if a customer initiates an order shortly before the restaurant's closure, the order is scheduled for the next day without adequate warning or explicit user action.

**Todo:**
1. Review the previous pull request for the redesign changes.
2. Identify any reasons for the changes not being retained.
3. Reintegrate the redesign changes into the codebase.

**Comment by Paul-Eraman-CoopCycle** [comment]
This needs to be made into a full design process thing i think...
it just keeps coming up over and over again, ill put in my todo list
