### ISSUE TITLE
My first experience as a user !

### ISSUE THREAD

**Issue by 0bi0ne1312** [coopcycle/coopcycle-app#1626]
FIRST TO KNOW, I am on an iPhone 12 PRO with a iOS 17.1.1 and coopcycle 2.9.0

I wanted to improve my knowledge on how it is working on the platform from a user POV.

I encountered various issues and lack of information returns that are here but not displayed.

- the font-color is the same as background-color so I could not see the address I am typing
- after putting the address on the favorite name page, when I click to put info, the block is going up and I can't see it anymore.
Same thing on filling personal info knfo page as a guest before ordering
- when on the menu of a restaurant, the special type tags (as vegan) are displayed on the palte page but not on the menu...
On the other way around, the photo is not displaying on the plate page but is on the menu one.
- when on the card filling info page, i don't have a proposition to use any of google nor apple wallet.
- finally, just as a graphic idea but I found the charging flat design gif is smoother and a bit nicer as the actual menu 😉

![image](https://github.com/coopcycle/coopcycle-app/assets/134289346/f9eebbbb-11c4-490c-b569-08713f1543d9)![image](https://github.com/coopcycle/coopcycle-app/assets/134289346/6c526cfa-bdc0-4320-b425-b9a59e4061d1)![image](https://github.com/coopcycle/coopcycle-app/assets/134289346/e2d9402c-b2c7-4858-aa7e-3c753ad7fc5e)![image](https://github.com/coopcycle/coopcycle-app/assets/134289346/a9875742-4777-471c-8380-74ff6ddff6d9)![image](https://github.com/coopcycle/coopcycle-app/assets/134289346/f013eef9-118a-4e5e-9feb-1c966969abf3)![image](https://github.com/coopcycle/coopcycle-app/assets/134289346/81d681f5-8fc9-4d71-bf51-a31a9b2c0280)![image](https://github.com/coopcycle/coopcycle-app/assets/134289346/5098a649-9025-48f6-a468-cdb3070504d1)![image](https://github.com/coopcycle/coopcycle-app/assets/134289346/96fb27b4-6dc9-4c82-a441-d0433ac6e526)

**Comment by vladimir-8** [comment]
Hi @0bi0ne1312, thank you for the feedback!

>     the font-color is the same as background-color so I could not see the address I am typing

That has been fixed.

>     after putting the address on the favorite name page, when I click to put info, the block is going up and I can't see it anymore.

Fixed in version 2.13.0 (not released yet)

>     Same thing on filling personal info knfo page as a guest before ordering

Also fixed in version 2.13.0 (not released yet)

>     when on the menu of a restaurant, the special type tags (as vegan) are displayed on the palte page but not on the menu...
>     On the other way around, the photo is not displaying on the plate page but is on the menu one.

Creating a separate issue for it: https://github.com/coopcycle/coopcycle-app/issues/1685 

> when on the card filling info page, i don't have a proposition to use any of google nor apple wallet.

There is already an issue for it: https://github.com/coopcycle/coopcycle-app/issues/1606

>     finally, just as a graphic idea but I found the charging flat design gif is smoother and a bit nicer as the actual menu 😉

Not sure if I understand what do you mean :) 

Closing this issue, If possible, next time please add a separate issue per topic, that will help us a lot in organising them
