### ISSUE TITLE
In order to valorize zero-waste delivery As a consumer I want zero-waste delivery activated by default

### ISSUE THREAD

**Issue by impec-dev** [coopcycle/coopcycle-app#1629]
**In order to**  `push zero-waste delivery system

**As a** `consumer

**I want** `zero waste delivery option to be activated by default (as per desktop) and have a pop up information as per UX designer mock up the first time I order. 

**Whereas currently**I need to activate it

**Additional context**
see Paul's the designer UX mock up
[](https://www.figma.com/file/e2p1XN912qCyBlQCMxLAhh/CoopCycle---IMPEC?type=design&node-id=1)

![tuto paul](https://github.com/coopcycle/coopcycle-app/assets/83373118/160b0d5b-a035-4fc7-81e3-ba985376a0cf)
33-1349&mode=design

**Comment by alexsegura** [comment]
I added a popup when the first zero waste enabled item is added to cart (like on the web version). 

What you are showing is something else, it's the "onboarding" / "how it works" popup. I think it should be shown when entering on a zero waste enabled restaurant. 

<img width="389" alt="Capture d’écran 2023-12-21 à 09 32 41" src="https://github.com/coopcycle/coopcycle-app/assets/1162230/f165e964-eea7-4e21-b6d3-264db8508e3d">
