### ISSUE TITLE
Use KeyboardAvoidingView

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-app#163]
On each screen where there is a submit button / form, we should use `KeyboardAvoidingView` to make sure the button stays clickable when the keyboard is visible. 

- [x] Add to credit card screen f2958ab9d5922b11e3968c0f2e70016ac7566428
- [ ] Add to login/register screen

https://facebook.github.io/react-native/docs/keyboardavoidingview

**Comment by alexsegura** [comment]
Actually, NativeBase already uses [KeyboardAwareScrollView](https://github.com/APSL/react-native-keyboard-aware-scroll-view), everything wrapped in `<Content />` is keyboard aware. 

It is important to be aware that the keyboard can't be hidden if the pressed `View` is not a `ScrollView`, so we need to use a `TouchableWithoutFeedback` to hide it when we are not using a `ScrollView`

Helpful article → https://medium.freecodecamp.org/how-to-make-your-react-native-app-respond-gracefully-when-the-keyboard-pops-up-7442c1535580

**Comment by alexsegura** [comment]
See f2958ab9d5922b11e3968c0f2e70016ac7566428 for an example

![credit-card-keyboard](https://user-images.githubusercontent.com/1162230/55293426-cd200a00-53f6-11e9-8138-e7e3eb740bcc.gif)

**Comment by ERAMANrepartos** [comment]
Status?

**Comment by Paul-Eraman-CoopCycle** [comment]
duplicate/related to #1650 , closing and tracking there
