### ISSUE TITLE
Display issue on the deposit management page

### ISSUE THREAD

**Issue by impec-dev** [coopcycle/coopcycle-app#1630]
**Describe the bug**
1. it doesn't work in dark mode
2. the + and - are displayed as "?" 
3. "créditer ma cagnotte" disappears when I return enough reusable packaging

**To Reproduce**
1. Go to a zero waste order with an existing account with reusable packaging in stock
5. Click on "checkout_loopeat_manager" (should be corrected in issue 1628)
6. Choose to give back some packaging
7. See the problem of display

**Expected behavior**
As per desktop (see screenshot) I should always have the "packaging return" menu + "add deposit" option + "deposit summary" in all situations.

**Screenshots**

https://github.com/coopcycle/coopcycle-app/assets/83373118/60818513-965e-40e1-8ef8-dd57fb9ff600

![dektop version](https://github.com/coopcycle/coopcycle-app/assets/83373118/d814a5fd-b304-4ece-abba-d93329e2c380)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alexsegura** [comment]
It will now look like this:


<img width="383" alt="Capture d’écran 2023-12-20 à 18 47 50" src="https://github.com/coopcycle/coopcycle-app/assets/1162230/3655f074-bc25-4c7d-835b-92604384fd56">
