### ISSUE TITLE
Search address bar’s text color is white when in dark mode, search bar background color is white

### ISSUE THREAD

**Issue by tcmjlnt** [coopcycle/coopcycle-app#1633]
**Describe the bug**
The text color switches from black to white but the background colors stays white, making it impossible to see what you're typing.

**To Reproduce**
1. Go to 'Coopcycle App'
2. Click on 'Address.'
3. Type text in the search bar
4. Switch to dark mode if in light mode
5. Keep typing
6. Text is white

**Expected behavior**
Text color should stay black

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - iOS 16.6
 - Coopcycle App 2.9.0

**Additional context**

https://github.com/coopcycle/coopcycle-app/assets/101735534/2626eb13-fc69-4914-870f-f01ad486a7be

**Comment by vladimir-8** [comment]
Can not reproduce it with the latest version: 2.12.0. Also tried on the iPhone SE, but with iOS 17.2:

https://github.com/coopcycle/coopcycle-app/assets/70273239/3fbb3813-3cb5-43db-a917-8d88bd76c6f1

Closing it for now, please re-open if it still happening

**Comment by vladimir-8** [comment]
I think it was fixed here: https://github.com/coopcycle/coopcycle-app/commit/b1374f8950750a88bb8798750c09f8924022d006#diff-df490c496e82579e2b43d6aff7fa3fec67df47a3c425f343ef066c468f6ab623R63
