### ISSUE TITLE
markdown text not being formatted in restaurant menu

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-app#1638]
look at Eatyjets
iphone

![image](https://github.com/coopcycle/coopcycle-app/assets/77277854/d141be1f-4c7d-47c2-b83d-c4845f097c54)

**Comment by r0xsh** [comment]
The description seems to note be visible in the new Design, i think this issue can be closed.
- New design: https://github.com/coopcycle/coopcycle-app/pull/1648

**Comment by alexsegura** [comment]
@r0xsh the description _may_ be shown when there are no tags.

https://github.com/coopcycle/coopcycle-app/blob/ae3da200f84af1189ec613f622a6191169358166/src/components/RestaurantCard.js#L131-L147

**Comment by alexsegura** [comment]
@Paul-Eraman-CoopCycle we are now using Markdown formatting. 

However, Eatyjet specifically is not using Markdown, but raw HTML, so this won't work in the app. 

So, for example: 

```html
<b>SOME LIKE IT HOT</b>, es una propuesta de <b>eatyjet</b>.
```

should be replaced by:

```markdown
**SOME LIKE IT HOT**, es una propuesta de **eatyjet**.
```

**Comment by r0xsh** [comment]
But it seems that's working on the web version. I think we should add [escape](https://twig.symfony.com/doc/3.x/filters/markdown_to_html.html) like this `{{ restaurant.description|escape|markdown_to_html }}` to avoid user to inject HTML

![Screenshot Eraman - Eatyjet - Some Like It Hot](https://github.com/coopcycle/coopcycle-app/assets/5613584/fcc305d5-c549-4e33-9fb8-8af79980a328)


https://github.com/coopcycle/coopcycle-web/blob/d39a05690583d345074939f852609596f0b96c04/templates/restaurant/index.html.twig#L177-L181
