### ISSUE TITLE
Cart summary is almost not readable in the dark mode

### ISSUE THREAD

**Issue by vladimir-8** [coopcycle/coopcycle-app#1651]
**Expected behavior**
Text colour should be easier to read.

**Screenshots**

![Simulator Screenshot - iPhone 15 - 2023-12-20 at 17 14 49](https://github.com/coopcycle/coopcycle-app/assets/70273239/40f393c7-351b-4eb3-ae55-555d531eb563)

**Comment by vladimir-8** [comment]
Will be fixed in https://github.com/coopcycle/coopcycle-app/pull/1658
![2023-12-27_115638-0676](https://github.com/coopcycle/coopcycle-app/assets/70273239/a22d339f-e9c9-40b6-9178-7e7ac7aded92)

**Comment by alexsegura** [comment]
Fixed in #1658
