### ISSUE TITLE
When the zero-waste option is activated, the switch off says "activate the zero-waste option" instead of "deactivate the zero-waste option"

### ISSUE THREAD

**Issue by impec-dev** [coopcycle/coopcycle-app#1692]
**Describe the bug**
When the zero-waste option is activated, the switch off says "activate the zero-waste option" instead of "deactivate the zero-waste option"

**To Reproduce**

**Expected behavior**
should say "deactivate the zero-waste option"

**Screenshots**

https://github.com/coopcycle/coopcycle-app/assets/83373118/d1fd4512-f7e1-4911-b91b-03093bfdefee

**Comment by alexsegura** [comment]
Obsolete, the UI has been changed to a checkbox in 79d8a008ef68e4da3f8c2d8022ba16ac95fb2b58, and we agreed that changing the text when toggling on/off doesn't make sense
