### ISSUE TITLE
Implement New Incident Handling for Task Failures

### ISSUE THREAD

**Issue by r0xsh** [coopcycle/coopcycle-app#1694]
Currently, the app allows riders to mark tasks as failed directly. However, we want to enhance this workflow by introducing a new method for handling task failures through incidents. Instead of riders directly marking tasks as failed, they will now declare incidents on tasks. These incidents will then notify the dispatcher, who will be responsible for assessing the situation and taking appropriate action, which may include marking the task as failed or other necessary steps.

To implement this new workflow, the app needs to stop using the existing `PUT /api/tasks/:id/failed` endpoint and start utilizing the newly introduced `PUT /api/tasks/:id/incidents` endpoint. This endpoint is specifically designed for handling incidents related to tasks.

See: https://github.com/coopcycle/coopcycle-app/issues/1679
See: https://github.com/coopcycle/coopcycle-app/issues/1680

**Comment by Paul-Eraman-CoopCycle** [comment]
working!
