### ISSUE TITLE
Customers "overnight orders"

### ISSUE THREAD

**Issue by GuillaumeNaofood** [coopcycle/coopcycle-app#1699]
**Describe the bug**
A customer can start his order before the end of a restaurant schedule. But when he presses the pay button, if Coopcycle calculates the order to late for the schedule, then the order suddently go for the next schedule available.
So it happens a lot, around the end of a shift, orders go the next day or the next next day if restaurant is closed tomorrow.
Most of the times, customers panics, restaurants can't see the order for today, and dispatch need to check the next day all the time otherwise he can miss it and lot of problems can appears.

**To Reproduce**
1. Go to a restaurant menu 5 min before it closed
2. Start an order by selecting articles
3. Check the order
4. Pay, and see the schedule changing at the end after the order validation

**Expected behavior**
We should have a warning information for the customer before the payment at least, or before :
Tell the customer that the restaurant is gonna closed and won't be able to make his order now. (with a pop-up)
OR
Have a timer all the time in the restaurant page corner to know if the order. This way, the customer can hurry himself.
OR
Block temporarily the order if it's gonna change schedule and go another service or day.

The customer can continues his order even if it's changing schedule, maybe he wants to pre-order.
But the real problem is that he can notice the changing schedule only after the payment and not before.

**Screenshots**

![1  Order B68N](https://github.com/coopcycle/coopcycle-app/assets/144671333/c9bed7a2-5e51-426e-8293-bd03c5dc7114)
![2  Screen orders tomorrow bug](https://github.com/coopcycle/coopcycle-app/assets/144671333/a57802f0-3182-41f3-aa6c-f7ade83303b6)
![3  Order B68N Export Coop ](https://github.com/coopcycle/coopcycle-app/assets/144671333/a1c2ffe8-9c5e-4dd7-ba8d-c90b604e2aad)

**Screen 1** : Order was made at 22:02 the 26th. We had to called the customer, he wanted it for tonight. The pick up timer was for lunch 12:13-12:23, it went overnight then.
**Screen 2** : We can see the order the the next day the 27th. We have to tell the rider to go the 27th on the app to deliver it. Before, we called the restaurant to check with him to do it right now and not for tomorrow.
**Screen 3** : Even if we delivered the B68N order the 26th night, in the coopcycle export order, it was accepted as the 27th. 
All the other orders are the same problem, some were made the 25th, the 26th... And some was canceled. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: Smartphone Oppo A72
 - OS: Android 10
 - Browser Google

**Additional context**
The biggest problem, is that it asks the dispatch to check and open others Panel Administration page to check if "overnight order" went for another day.

**Comment by vladimir-8** [comment]
We discussed it briefly. It seems that the first/most straightforward step could be not to reschedule automatically to the next day or even to a time slot more than 2? hours later than the original one. We can show a message in that case, and if a customer wants to pre-order, they would explicitly select a preferred time slot. What do you think? (cc @Paul-Eraman-CoopCycle )

**Comment by GuillaumeNaofood** [comment]
> It seems that the first/most straightforward step could be not to reschedule automatically to the next day or even to a time slot more than 2?
It won't have any effects elsewhere ? Like people that orders with "as soon as possible" tag ?

But yeah, defenitely. With a pop-up message that warns the customer from this reschedule, and make him selecting manually a time slot delivery if it's a pre order. It's perfect !

**Comment by Paul-Eraman-CoopCycle** [comment]
What makes me most nervous is that I have heard some people want

1. to avoid these orders happening. they want to have something that communicates well that the restaurant is going to close and therefore the client orders in time, and if not, they dont get food. (this is actually quite hard. pop up maybe, but we also dont want to make lots of pop ups that fuck with the purchase process, how does the pop up get triggered....)

2. to make it so people realize these orders are happening so that they can reschedule them for the same night even if manually (they dont want to loose the job, even if its extra work)

and i dont know how to combine those two things...

**Comment by GuillaumeNaofood** [comment]
Maybe... The answer can be a timer that tells the remaining time for the last order ! I cna picture this timer in the corner of the screen after selecting a restaurant. It sticks to the corner until the payment ?

And after this timer, it blocks the orders for the night and open the schedule option with only tomorrow or tonight next shift available ?

**Comment by Paul-Eraman-CoopCycle** [comment]
I know that some cooperatives will say that this will descourage people from making orders at the end of the night

which is true, but i also agree with you...

i think maybe we need a meeting with a few people to discuss from food coops, what do you think?

**Comment by Paul-Eraman-CoopCycle** [comment]
we have made the timing modal developments to fix these issues which are deployed in web and are now being finished up in the app, we can track there so im going to close this issue here
