### ISSUE TITLE
The order of the tasks in the dispatch app is not correct - it is correct in the rider part of the app

### ISSUE THREAD

**Issue by lillebike** [coopcycle/coopcycle-app#1700]
**Describe the bug**

**To Reproduce**
1. Go to 'admin dashboard'
2. assigne tasks in a certain order
4. go to app See error

**Expected behavior**
The tasks should stay in the right order

**Screenshots**
![ordretasks](https://github.com/coopcycle/coopcycle-app/assets/146206239/295a5a3d-0ce4-41a1-bee5-8da041389d50)
![signal-2024-03-01-133009_002](https://github.com/coopcycle/coopcycle-app/assets/146206239/eb3f0b71-4b78-4d7a-8a74-83f0754602be)

**Desktop (please complete the following information):**
 -microsoft, chrome

**Smartphone (please complete the following information):**
ulefone armor 3

**Additional context**
I received an order this morning, assigned it to yohann
later on I got into dispatch mode on the app to validate 2 of his tasks that i did myself, it happened that the last tasks I assigned him (on my computer earlier) appeared last which means that he may have missed it as they appeared after tasks that had to be done at 18h

**Comment by Atala** [comment]
@lillebike 
- did you do stuff with tasks like reorder them?
- do you know how it looks in yohann app? can you check? (even better send a screenshot)

**Comment by lillebike** [comment]
Hey
I reordered them on the laptop in the order that is on the screenshot but not after that
I asked yohann he told me it was in the right order on his phone
we both use android

**Comment by lillebike** [comment]
as un update, yesterday it did the same again on my app in the rider part (updated the app and tried again it was still pick up/ drop off/ pick up/drop off etc...)
phone is ulefone armor 3x android

**Comment by Atala** [comment]
@lillebike do you use "Tournée/routes" ? or just "normal" tasks/dispatching?

**Comment by Atala** [comment]
OK, I have fix it in the last version I think i will push it to you and you tell me

**Comment by Atala** [comment]
I will tell you when i have deployed the new version to your instance

**Comment by Paul-Eraman-CoopCycle** [comment]
waiting to test for all routes dispatch issues to be ready to test together

**Comment by Atala** [comment]
@lillebike can you contact me if it happens again?
