### ISSUE TITLE
Green button to move orders from one column and state to the next

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-app#1708]
A button in the main interface (without opening the order) that moves it from one column to the next, until it is "finished" which then has no more actions by the restaurant

design: https://www.figma.com/file/QhKPMWQJqQBLBgjwGVlIpk/Restaurants?type=design&node-id=633-14535&mode=design&t=afhR1F9msuDNOn5Z-0

**Comment by vladimir-8** [comment]
Demo:

https://github.com/coopcycle/coopcycle-app/assets/70273239/d2367bd4-8246-4c64-b9ac-b7a7c4830404

https://github.com/coopcycle/coopcycle-app/assets/70273239/49692f7f-e5c7-49ce-90e2-417eb17b022e
