### ISSUE TITLE
impossible to validate top task on the app

### ISSUE THREAD

**Issue by lillebike** [coopcycle/coopcycle-app#1720]
**Describe the bug**
today on my phone and my college phone, we have been anable to validate the first task (task number #12538 and #12540) of our list in courrier mode

**To Reproduce**
1. Go to 'tasks'
2. Click or slide on 'first task'
3. 
4. See error nothing happens

**Expected behavior**
it's supposed to open the task or when we slide it we are supposed to be able to validate the task

**Screenshots**

https://github.com/coopcycle/coopcycle-app/assets/146206239/b4c2e476-07f5-4fb0-8af1-b18dab4ec3ed

**Desktop (please complete the following information):**
 - 
 

**Smartphone (please complete the following information):**
 - sony xperia: android
 ulephone armor x3:android

**Comment by alexsegura** [comment]
Fixed in #1716
