### ISSUE TITLE
Cant close tasks with comments?

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-app#1737]
**Describe the bug**
When a comment is added to the task, it cannot be clsoed

**Expected behavior**
even with a comment it can be closed

**Screenshots**
![telegram-cloud-photo-size-4-5854834624486818129-y](https://github.com/coopcycle/coopcycle-app/assets/77277854/c034f90b-59d9-4f2d-84a3-a41cd47bb2d8)
![telegram-cloud-photo-size-4-5796314909099802419-y](https://github.com/coopcycle/coopcycle-app/assets/77277854/ef37ca23-0468-4ee0-b92b-68455eb40bb2)

**Comment by r0xsh** [comment]
Huh hard to tell, is it still a thing that happen ?

May be related from what i just fixed: https://github.com/coopcycle/coopcycle-web/commit/ec93aaeaba20a70828cf630670a4a99148feaa96
