### ISSUE TITLE
Restaurants do not recieve new orders; "Connexion lost, trying to reconnect"

### ISSUE THREAD

**Issue by vladimir-8** [coopcycle/coopcycle-app#1738]
**Describe the bug**

Here is a persistent new restaurant bug on their app.
There were this problem before, with a bad wifi connexion, a yellow line was marked with "Connexion lost, trying to reconnect". But it was still possible to received orded even in this state. It was a visual thing / problem, it didn't block orders.
But now, it's different, it's pretty common. 6 restaurants got this problem at the moment.
And it's impossible for them to receive orders in this yellow state bar.
And it doesn't seems to budge, to reconnect. This state stay still and blocks orders.
This restaurants wifi and internet didn't change.
They didn't had this problem before the update, so I guess, the new app disconnect more easily or it doesn't auto reconnect maybe ?

**Additional context**

https://coopcycle.slack.com/archives/C4UT4DGQ3/p1712156452234059

**Comment by vladimir-8** [comment]
Checked logs for a few restaurants, did not find anything suspicious. I found an earlier issue related to Centrifugo (the system behind this green/yellow status bar). I think we should start with upgrading it and see if it improves the situation: https://github.com/coopcycle/coopcycle-web/issues/3617

**Comment by Paul-Eraman-CoopCycle** [comment]
closing for now
