### ISSUE TITLE
setting icon is not visible for rider in light mode, only in darkmode

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-app#1741]
slack conversation https://coopcycle.slack.com/archives/C4UT4DGQ3/p1712327028519519

light mode : 
![photo_2024-04-05_16-19-49](https://github.com/coopcycle/coopcycle-app/assets/4426585/1e852105-4706-438d-b0fb-06c3624a34d0)

dark mode : 
![Screenshot_20240405_162436_CoopCycle](https://github.com/coopcycle/coopcycle-app/assets/4426585/fb5e114e-395c-4de0-a01d-1096d36b83e6)

**Comment by v-lozko** [comment]
I wouldn't mind giving this one a try

**Comment by v-lozko** [comment]
Hey @Atala, I've just having been too much issues with getting it working on my device, it may be best to have someone who can get the simulator going to look at this

**Comment by Atala** [comment]
hello @v-lozko that is the shame if you can't contribute.  it is true that the app can be a hassle to setup. can you reach me out at alois[at]coopcycle.org and I can help you to figure things out. it is just that now i dont see anyway to contact you on your github profile

**Comment by v-lozko** [comment]
Hello, I replied to your email but just wanted to say it here as well, but I dont have the capacity to look at this so if someone else wants to take it they can.
