### ISSUE TITLE
Unable to connect to any instance on Android 7

### ISSUE THREAD

**Issue by vladimir-8** [coopcycle/coopcycle-app#1744]
No cities + URL doesn't work

**Screenshots**

![IMG_20240404_200345](https://github.com/coopcycle/coopcycle-app/assets/70273239/947fe844-34b3-4b53-a7ba-c24987404763)
![IMG_20240404_200403](https://github.com/coopcycle/coopcycle-app/assets/70273239/a859b297-083b-419d-901b-c70b46569442)
![IMG_20240404_200900](https://github.com/coopcycle/coopcycle-app/assets/70273239/afd06eec-ec9c-409c-b11d-fa71023dc680)

**Smartphone (please complete the following information):**
 - OS: Android 7

**Additional context**

https://coopcycle.slack.com/archives/C4UT4DGQ3/p1712253937287019

**Comment by vladimir-8** [comment]
Happens on Android version 6.0.1 too, https://coopcycle.slack.com/archives/C4VH560ES/p1713357245783889

**Comment by Paul-Eraman-CoopCycle** [comment]
Looks like we dont support android 6 or 7 then
