### ISSUE TITLE
Rayo/Zampate local commerce app doesnt create orders

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-app#1753]
Shop : enredadas https://zampate.coopcycle.org/admin/stores/45

Request from app : `curl -X POST  -H "accept:application/json, text/plain, */*" -H "content-type:application/ld+json" -H "x-coopcycle-app-version:2.16.4" -H "x-application-version:fr.coopcycle@2.16.4 (203)" -H "<auth_token>" https://zampate.coopcycle.org/api/deliveries -d '{"store":"/api/stores/45","dropoff":{"address":"/api/addresses/25420","before":"2024-04-24T11:15:24+02:00","timeSlot":"2024-04-30 09:00-15:00"}}'`

- fails also with a non-saved address
- does not fail when unticking "create order"

crash in sentry: https://coopcycle.sentry.io/issues/4493424490/?project=5294179&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=1

so the **address is not set on one of the tasks**

```
    private function calculate(TaskCollectionInterface $taskCollection)

    {

        $coordinates = [];

        foreach ($taskCollection->getTasks() as $task) {

            $coordinates[] = $task->getAddress()->getGeo();

        }
```

https://github.com/coopcycle/coopcycle-app/assets/77277854/598e0469-76d5-42be-a70b-b36e3ee43716

**Comment by Atala** [comment]
@Paul-Eraman-CoopCycle i can look at it but i would need the original slack thread and the name of the store

**Comment by Paul-Eraman-CoopCycle** [comment]
tested and working now 🥳
