### ISSUE TITLE
Restaurant product badge redesign

### ISSUE THREAD

**Issue by Pierre-LHOSTE** [coopcycle/coopcycle-app#1760]
Badges should be displayed in the same style:

|list: |details: |
|-|-|
|![Simulator Screenshot - iPhone SE (3rd generation) - 2024-03-27 at 17 04 37](https://github.com/coopcycle/coopcycle-app/assets/70273239/e3b377af-b416-4f2a-a733-ac83941401e8) |![Simulator Screenshot - iPhone SE (3rd generation) - 2024-03-27 at 17 04 41](https://github.com/coopcycle/coopcycle-app/assets/70273239/402f90fc-4294-4f62-96ec-1d253c186486) |

_Originally posted by @vladimir-8 in https://github.com/coopcycle/coopcycle-app/pull/1719#discussion_r1542177773_

**Comment by Pierre-LHOSTE** [comment]
Fix in https://github.com/coopcycle/coopcycle-app/pull/1757

**Comment by Paul-Eraman-CoopCycle** [comment]
not closed until its in the finished column! sorry 🙏
