### ISSUE TITLE
Task list's settings button does not appear in light mode

### ISSUE THREAD

**Issue by vingt-douze** [coopcycle/coopcycle-app#1762]
| Light | Dark |
|-|-|
| ![](https://github.com/coopcycle/coopcycle-app/assets/90503814/820b503e-ac56-40c3-835f-569805536213) | ![](https://github.com/coopcycle/coopcycle-app/assets/90503814/03344041-fa9a-46f2-add8-0bed8f202c03) |

**Comment by Pierre-LHOSTE** [comment]
Duplicate of https://github.com/coopcycle/coopcycle-app/issues/1741
