### ISSUE TITLE
The topbar no longer follows the main theme

### ISSUE THREAD

**Issue by r0xsh** [coopcycle/coopcycle-app#1768]
![Screenshot_20240422-165903_CoopCycle.png](https://github.com/coopcycle/coopcycle-app/assets/5613584/c9cc7dee-9f9b-4470-80f8-6e0c06ce0424)

![Screenshot_20240422-165914_CoopCycle.png](https://github.com/coopcycle/coopcycle-app/assets/5613584/b89700b5-386b-4377-879a-1b30314833e6)

https://coopcycle.slack.com/archives/G01JR0YF5V3/p1713796479607169?thread_ts=1713796479.607169&cid=G01JR0YF5V3

https://coopcycle.slack.com/archives/C4VH560ES/p1712566742251929?thread_ts=1712516191.345259&cid=C4VH560ES

**Comment by vladimir-8** [comment]
Duplicates https://github.com/coopcycle/coopcycle-app/issues/1772
