### ISSUE TITLE
New order with a prior timing than the "ding" timing.

### ISSUE THREAD

**Issue by KilliaNaoEraman** [coopcycle/coopcycle-app#1774]
**Description:**

A new order comes in at 12:10AM.
Order is marked to be picked up at 12:02AM.

**Reproducing:**
We don't know yet how this can be reproduced.
From customer's feedback it seems he took some time to order. So perhaps a timing was locked before the order was actually there?

**Expected behavior:**
Timings in the future so that the restaurant doesn't have to use a time machine to go back in the past to prepare the order!
If "ding" 12:10AM > Pickup Timing should be 12:20AM More or Less according to each restaurant's prep time.

**Screenshot:**
![image](https://github.com/coopcycle/coopcycle-app/assets/166378867/8d1e0479-e77f-47b9-a22f-a268cf9f2e4c)

Standard devices.
**Naofood Order BMDE**

**Additionnal context:**
This bug is likely to be very new and linked to last updates.

**Comment by vladimir-8** [comment]
Closing this issue, as we have the same issue planned: https://github.com/coopcycle/coopcycle-web/issues/4091
