### ISSUE TITLE
Make sure notifications are not sent anymore when user has logged out

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-app#178]
For long time my coopcycle tablet app was connect with my admin account. Last week I changed it to a restaurant account because one of my restaurant partners had some problems with his Iphone app and I lend it my tablet with his account. Today his iphone problems is resolved but I don't take time to change again the account in the tablet. And I received a coopcycle notif with the tablet. 
Problem : there was no command but one command for another restaurant.

**Comment by alexsegura** [comment]
Ok, I understand. 

The problem is that the push notification token sent to the server is not revoked when the user logs out, resulting in wrong notifications sent. 

We should send a request to the server telling to revoke the token when logging out.
