### ISSUE TITLE
New delivery; re-organise and re-style pages (Dropoff)

### ISSUE THREAD

**Issue by vladimir-8** [coopcycle/coopcycle-app#1789]
## Context
Right now we have a first page that only asks for an address and is very blank, then a second page with many items. In total, we are missing many elements. We must reorganize to have a good distribution between pages and a coherent story for each page. The concept would be to have the first page be client info, and the second page be order-specific info such as package, timing, etc. (client remains the same over multiple orders, packages and time slots may not)

#### 1st page Current Design
![35F97E93-5C20-4AB8-B322-DD57D1803174_1_102_o](https://github.com/coopcycle/coopcycle-app/assets/77277854/a81d9829-5396-4eba-b041-ea6c4b38e02b)

#### Things to change:

- [x] add client list search function that automatically populates the rest of the page (optional)
- [x] add business name field (optional) 
- [x] move address field from 2nd page to first page (obligatory)
- [x] move who to contact field from 2nd page to first page (obligatory)
- [x] move phone number from 2nd page to first page (obligatory)

#### 1st page New Dirty Design
<img width="250" alt="Screenshot 2024-05-24 at 22 38 22" src="https://github.com/coopcycle/coopcycle-app/assets/77277854/87df0560-300b-41f7-a839-05193d9ff528">

#### 1st page Finished Design
TO DO

**Comment by Paul-Eraman-CoopCycle** [comment]
The client search bar is returning all past delivery addresses, not address book. otherwise, this is working.
Made subissue
