### ISSUE TITLE
New delivery; Show price before finishing

### ISSUE THREAD

**Issue by vladimir-8** [coopcycle/coopcycle-app#1793]
Show only Total price for now, later on: https://github.com/coopcycle/coopcycle-app/issues/1885

**Comment by alexsegura** [comment]
The `/api/retail_prices/calculate` endpoint can already be used for this. 

We just need to make sure to send the `store` property in the payload, like in this example: 

https://github.com/coopcycle/coopcycle-web/blob/a8f2df6cbdd117cfe6fed97774a338354bbf3b9b/features/retail_prices.feature#L18-L28

**Comment by vladimir-8** [comment]
@Pierre-LHOSTE to make it consistent with the current web implementation, we should not allow a `store` owner to proceed if a price can not be calculated. We will work on it in https://github.com/coopcycle/coopcycle-web/issues/4557

![Image](https://github.com/user-attachments/assets/8e933540-c1b3-4a07-9d9d-85339df2fecc)
