### ISSUE TITLE
Infinite loading page for payment

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-app#18]

**Comment by couleurmate** [comment]
Okay, only working for card 4242 ;)

**Comment by Atala** [comment]
It is is indeed a bug.

Which isntance? Molenbike or demo?

**Comment by couleurmate** [comment]
molenbike

**Comment by alexsegura** [comment]
I think this is fixed in 89dcaaf1eed3ade6101304bbabff28d8da6eae84

Please reopen if needed
