### ISSUE TITLE
Not enough informations on restaurant screen

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-app#182]
- [x] Add restaurant image on top of page 07a4b417cb9c248b5bfe6bda33c1ac4287331c7a
- [x] Add restaurant name, description & opening hours

**Comment by TifaineSicklo** [comment]
Opening hours is really important, i test a restaurant tonight (la crapaudine), it closed tonight and tomorow and client can command even if it's close.

**Comment by ERAMANrepartos** [comment]
I´m closing this issue because it has technically been completed. 
That said, it is highly inefficient. The opening hours are only delivery hours, which can be confused for general opening hours. The descripcion UI isn´t great especially in mobile. We need to rework this from the ground up frankly.
