### ISSUE TITLE
Rider needs to see if an order is a zero-waste order

### ISSUE THREAD

**Issue by impec-dev** [coopcycle/coopcycle-app#1822]
**In order to**  be informed, prepare carrying material and checked the restaurant preparation

**As a** rider

**I want** to have an icon near the task to see it is in resable container

**Whereas currently** `I need to enter the description

**Additional context**
![résumé des taches](https://github.com/coopcycle/coopcycle-app/assets/83373118/4559f1e1-3ba8-40b6-937d-6c259529bfe1)

**Comment by alexsegura** [comment]
It will look like this:

![Image](https://github.com/user-attachments/assets/b5712876-419a-4fa6-9370-20a7c80636b3)
