### ISSUE TITLE
time range is wrong for a foodtech order

### ISSUE THREAD

**Issue by KilliaNaoEraman** [coopcycle/coopcycle-app#1832]
![coopcycledem](https://github.com/user-attachments/assets/698a74d8-b438-4e2c-8ef4-7629c3dd0d5c)

Order comes in at 19H27, we have to pick it up in between 18H34 and 18H44 and drop it between 19H and 21H15...

**Comment by Paul-Eraman-CoopCycle** [comment]
what happened?

**Comment by KilliaNaoEraman** [comment]
Seems like it was the restaurant's timing that wasn't properly scheduled
