### ISSUE TITLE
edenred order was accepted, shouldnt work yet

### ISSUE THREAD

**Issue by KilliaNaoEraman** [coopcycle/coopcycle-app#1833]
Edenred order is accepted whereas it is not supposed to work yet. See screens.
![image](https://github.com/user-attachments/assets/8b140edc-7472-427e-9898-6e1ce2d92f73)
![Screenshot_2024-07-10-15-05-38-74](https://github.com/user-attachments/assets/39c208b9-5b23-4b8f-b078-491a8b89c521)

**Comment by alexsegura** [comment]
Sorted out with Edenred support, it's actually a UX problem: customer entered Edenred card number into credit card field.

**Comment by Paul-Eraman-CoopCycle** [comment]
Is there a way to validate the number of digits or something to avoid this?
