### ISSUE TITLE
cannot bulk validate tasks if there is the pick up and the drop off in the same "bulk"

### ISSUE THREAD

**Issue by lillebike** [coopcycle/coopcycle-app#1835]
**Describe the bug**
After recent updates of the app,sometimes it refuses to validate a pick-up and a drop off at the same time

**To Reproduce**
1. Go to 'course'
2. select several task including pick ups and drop offs of the same order
3. validate
4. App refuses to validate the drop offs

**Expected behavior**
we used to be able to validate several tasks at the same time

**Screenshots**
![WhatsApp Image 2024-07-16 at 15 09 16](https://github.com/user-attachments/assets/2041022f-5c81-4b74-be6c-20d71d8c95de)

**Device (please complete the following information):**
 - pixel 7
 - Android
 - App version 2.20.0 
 Android 14

sometimes i need to bulk validate tasks as I haven't validate threw out the day and it validate all the pick ups and ask me to do again the process for the drop offs

**Comment by Paul-Eraman-CoopCycle** [comment]
not planned currently, the workflow imagines that pickups and dropoffs are validated in separate actions
