### ISSUE TITLE
application crash before payment

### ISSUE THREAD

**Issue by HugoLCR** [coopcycle/coopcycle-app#1842]
**Describe the bug**
After several tries, the personalized LCR app on ANDROID crashes on first use (only), between step 3 and payment.
This situation only occurs when we first open the app, and when we are in "guest" mode.

**To Reproduce**
1. delete the app
2. download again without logging in
3. generate an order in "guest" mode
4. go to payment
5. the app crashes

**Expected behavior**
the app remains open and I can enter my banking details

**Screenshots**

**Device (please complete the following information):**
 - Device: [Pixel 6a]
 - OS: [Android 13]
 - Browser or App Version [App Les Coursiers Rennais 2.23.0]

**Additional context**
the bug only occurs on the first opening of the app, and only in guest mode

https://github.com/user-attachments/assets/14c90ed0-143f-4ed7-8022-bba7fdf5b6ff

https://github.com/user-attachments/assets/cb32c2fa-421e-4e55-b39f-068ae8d20cc7

**Comment by vladimir-8** [comment]
Thanks for reporting @HugoLCR ! That's the same issue as this one: https://github.com/coopcycle/coopcycle-app/issues/1841 I will track it there
