### ISSUE TITLE
Bluetooth printer prints ticket three times

### ISSUE THREAD

**Issue by HugoLCR** [coopcycle/coopcycle-app#1844]
**Describe the bug**
the restaurant prints the ticket on the bluetooth printer, and 3 same tickets come out

**To Reproduce**
print a ticket from the restaurant interface on the application

**Expected behavior**
the ticket comes out once

**Device (please complete the following information):**
 - Iphone 15
 - iOS 17
 - app Coopcycle 2.23.0

**Comment by vladimir-8** [comment]
Duplicates: https://github.com/coopcycle/coopcycle-app/issues/1839 Will track it there
