### ISSUE TITLE
Clickable link in task comment

### ISSUE THREAD

**Issue by 0bi0ne1312** [coopcycle/coopcycle-app#1850]
In order to be able to access to more infos, it would be great to "allow" clickable data from the comments of a tasks

For an example, if I need to put a second phone number, I would have to put it in the comment section but I cannot access it from the courier side to call it directly or even just to copy / paste it that would be the least I would need.

Also, it is a feature I already heard of from other structures to have links in that section for some clients that need more infos about the delivery in google form type of external docs. In that case, putting a link in the comment section as the dispatcher (or even in the comment/info section of a registered address of a client) that can be clickable from the courrier app would be a great feature !

<img width="1582" alt="Capture d’écran 2024-08-20 à 13 48 03" src="https://github.com/user-attachments/assets/3c699f58-d27f-4dff-8f49-ecd5c7a72620">
<img width="1582" alt="Capture d’écran 2024-08-20 à 13 51 06" src="https://github.com/user-attachments/assets/8baa652d-98eb-48a3-a5c3-df6f0f548458">

**Comment by 0bi0ne1312** [comment]
![Linktest](https://github.com/user-attachments/assets/2cd8a638-3a90-4be8-8461-2f0b589a0e18)

**Comment by Paul-Eraman-CoopCycle** [comment]
Not currently planned, closing

For future planning, how often is this useful @0bi0ne1312 ?

**Comment by 0bi0ne1312** [comment]
It was asked from some structures like Krokoop and Montpellier for some clients using it.

Also, as we can't put any pdf in the delivery request (useful to add barcode for retrieving an order), having clickable link in the comment area is really useful.

**Comment by Paul-Eraman-CoopCycle** [comment]
Ill ask how hard this is and get back to you

@alexsegura @Atala @r0xsh @vladimir-8

**Comment by alexsegura** [comment]
We could allow Markdown in comments, but it would mean having a Markdown editor in the dispatch panel. 
But IMHO it's the wrong solution, it would be prone to unexpected errors. Markdown support on the app is limited, the rendering can't be guaranteed. 

Instead, I would go for a first-class citizen feature "attach a URL to the task".

**Comment by Paul-Eraman-CoopCycle** [comment]
@0bi0ne1312 those pdfs, where are they stored? like, a url will allow access to them?

**Comment by 0bi0ne1312** [comment]
For now they are sent by mail by our clients so they could just put a link

**Comment by Paul-Eraman-CoopCycle** [comment]
What is the link to then? A email in gmail or something?

**Comment by r0xsh** [comment]
This can be easily achieved and seems to be requested a lot, i reopen this issue

Resources:
https://markdown-it.github.io/linkify-it/doc/
https://github.com/obipawan/react-native-hyperlink
