### ISSUE TITLE
The function "makeLabel" may return "Today between"/"Aujourd'hui entre" although the delivery is for tomorrow

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-app#1891]
delivery starts at 2024-10-03T15:08:00.000Z
now is 2024-10-02T15:41:37.034

-> the delivery is for tomorrow but in Delivery.js it is displayed as "for today"

![Image](https://github.com/user-attachments/assets/a4acda84-4250-471a-8dde-99f4ab2b02d7)

the problem lies in makeLabel function I think. the calendarFormat function don't do what you think it does.
```
function makeLabel(range, now) {
  if (range.diff('days') === 0) {
    const nowClone = moment(now)
      .set('hour', range.start.get('hour'))
      .set('minute', range.start.get('minute'))
      .set('second', range.start.get('second'));

    console.error(range.start)
    console.error(now)
    console.error(moment.calendarFormat(range.start, nowClone))

    // This will return the key used in moment.calendar()
    // https://momentjs.com/docs/#/displaying/calendar-time/
    let calendarFormat = moment.calendarFormat(range.start, nowClone);
```

**Comment by Atala** [comment]
@alexsegura @vladimir-8

**Comment by vladimir-8** [comment]
```
range.diff('days') === 0
```

If that's a way to check if it's `today` or not, then may be we should use something like `moment('2010-01-01').isSame('2010-02-01', 'day');` instead

**Comment by Atala** [comment]
it is a way to check if the delivery dropoff is spanning on more than one days
so this or moment(range.start).isSame(range.end, 'day') should do the same
