### ISSUE TITLE
restaurants' tablets dont ring when they get a New order while the app is in the background

### ISSUE THREAD

**Issue by vladimir-8** [coopcycle/coopcycle-app#1895]
**Additional context**

https://coopcycle.slack.com/archives/CQDUL440P/p1728065268958869

**Comment by vladimir-8** [comment]
When fixed apply the same approach to https://github.com/coopcycle/coopcycle-app/issues/1836

**Comment by alexsegura** [comment]
All apps work this way, even messaging apps, which have the same "problem", i.e I want to know about it immediately when I receive a new message. If you turn off notifications, if you put your phone in silent mode... you may miss the notification.
