### ISSUE TITLE
address search bar not working in dark mode

### ISSUE THREAD

**Issue by HugoLCR** [coopcycle/coopcycle-app#1917]
**Describe the bug**
address search bar not working in dark mode

**To Reproduce**
1.look for an address in the bar
2. See error

**Expected behavior**
see my address

**Screenshots**
![Image](https://github.com/user-attachments/assets/d2010263-8202-47ee-805f-102914809c13)

**Device (please complete the following information):**
Android 12
Pixex 6A
APP LCR

**Additional context**
it works in clear mode

**Comment by vladimir-8** [comment]
Fixed in https://github.com/coopcycle/coopcycle-app/pull/1908
