### ISSUE TITLE
Wrong timezone offset on some devices

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-app#192]
On some devices, when displaying dates returned by the API, the timezone offset is wrong. 

There are 2 problems: 

1/ It seems that even when changing the timezone in Android settings, the timezone is not applied until a reboot, even if the hour displayed by the device OK. 

2/ Dates returned by the API indeed contain the timezone offset (ex: `2019-05-19T09:45:00+02:00`). But we should be using `moment.parseZone(value)` instead of `moment(value)` to properly parse the timezone offset.

> moment(...) is local mode. Ambiguous input (without offset) is assumed to be local time. Unambiguous input (with offset) is adjusted to local time.
> moment.parseZone() keep the input zone passed in. If the input is ambiguous, it is the same as local mode.

See [Local vs UTC vs Offset](https://momentjs.com/guides/#/parsing/local-utc-zone/)

**Comment by alexsegura** [comment]
In 406003fc2d99e20026cd6e5b72966a0a340b9995 we are using `moment.parseZone` as a hotfix.

Not sure what is best...
We could also return the timezone of the connected server in `/api/settings` endpoint, and use [moment-timezone](https://momentjs.com/timezone/docs/#/using-timezones/default-timezone/) to set it globally?

**Comment by alexsegura** [comment]
Maybe some clues in react-native-community/react-native-localize#65

**Comment by Paul-Eraman-CoopCycle** [comment]
Until we hear that this has happened again, closing as not planned

**Comment by Paul-Eraman-CoopCycle** [comment]
Is a general problem we have with how time is stored on our database
