### ISSUE TITLE
mauvais frais de livraison

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-app#207]
Excusez-moi je vais encore utiliser le français mais le problème est trop technique pour que j'y arrive en anglais.
Voilà j'ai remarqué que sur l'app, quand le client fait sa commande, dès qu'il choisit un produit, ça lui rajoute des frais de livraisons même si le restaurant ne met pas de frais de livraisons. En fait ça met le montant que je facture au restaurant sur chaque commande en frais de livraison pour le client. Vous avez compris ?

**Comment by alexsegura** [comment]
Oui je vois le problème. 

Mais normalement, c'est juste de l'affichage. 
Si tu passes commande, les bons frais sont calculés. 

Je vais corriger ça.

**Comment by alexsegura** [comment]
Fixed in df569b4426eb353ffd35bcaf3ce97fdf68c59b17
