### ISSUE TITLE
Use Firebase Analytics

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-app#208]
Using Matomo for screen tracking was not a good idea. 

[Firebase Analytics](https://firebase.google.com/docs/analytics) seems the way to go.

**Comment by vova1vova** [comment]
I was actually considering using Matomo :) What was an issue with it?

**Comment by alexsegura** [comment]
We used Matomo, yes, but: 

1/ The [React Native plugin](https://github.com/BonifyByForteil/react-native-matomo) is not maintained actively, it was quite hard to get it working.
2/ The web traffic is mixed with the app activity, and was increasing artificially web traffic.

Actually, app tracking & web tracking are quite different things. It's 2 different "channels".
Firebase offers better tools for app tracking.

**Comment by alexsegura** [comment]
Fixed in 1486e50be0ad0cb1e90ed507a62ce323b6f4e8a6
