### ISSUE TITLE
Performance issues with map clusters

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-app#210]
Reported by @couleurmate 

> When a lot of clusters are displayed at the same time (a dozen), the app is slow as fuck
> Almost impossible to zoom or navigate
> 85 tasks, lot of clusters, super slow on street level zoom

**Comment by alexsegura** [comment]
Maybe related novalabio/react-native-maps-super-cluster#97

**Comment by alexsegura** [comment]
Some optimizations

312ed9b73c31abce4bdda02c4ebc59f08345cf26...2e2d8be0003759c1d1a9504a976305c8ffd48993

**Comment by alexsegura** [comment]
Some more optimisations b31db24795cf890ce538d8afbadaaa136a943e96

**Comment by ERAMANrepartos** [comment]
I believe this is now better, so I´m going to close. @alexsegura please confirm and reopen if necessary
