### ISSUE TITLE
Auto-center map on courier on task screen

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-app#215]

**Comment by couleurmate** [comment]
https://coderwall.com/p/hojgtq/auto-center-and-auto-zoom-a-google-map

**Comment by ERAMANrepartos** [comment]
This seems like the same as #216 but i imagine not considering that you made the issues at the same time. Could you clarify the difference? @couleurmate

**Comment by Paul-Eraman-CoopCycle** [comment]
closing as repeat issue/not planned
