### ISSUE TITLE
Track-up map orientation on task screen

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-app#216]
When you're heading to the marker location, you wanna checkup your position. It would more intuitive if map would be following user compass or user movement

**Comment by alexsegura** [comment]
You mean that in landscape mode, the map should be on the left?

**Comment by ERAMANrepartos** [comment]
I believe they are saying that when you reopen the app during a delivery, in route to a pickup or dropoff, instead of the map being center to where you last looked (a small area where you last task was, surely), it could show a prefigured zone (1 zq km for example) around your current geolocation.

**Comment by Paul-Eraman-CoopCycle** [comment]
not currently planned, closing
