### ISSUE TITLE
Back to main task map from task id screen

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-app#26]
Now, user has to click on the back arrow. 

Options are :
- click on map to get back to main task map
- finishing or failing get automatically back to main task map

**Comment by alexsegura** [comment]
Partially fixed in 8dfba329943553a795ceb686db9e755ccd22dd44

![tasks_goback](https://user-images.githubusercontent.com/1162230/36371842-9bbadf08-1563-11e8-9fb6-c7ede0df0413.gif)
