### ISSUE TITLE
Remote push notifications

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-app#27]
One has to reload `My Task` screen to fetch new assigned tasks

**Comment by alexsegura** [comment]
Yes, this is something we are going to implement. 

Until we setup APNS & GCM, we are going to use local notifications with [react-native-push-notification](https://github.com/zo0r/react-native-push-notification)

**Comment by alexsegura** [comment]
Tasks are updated in 9d25848309fefa24e4265d6f7ca3b9aa5c45c3bb

The work to handle notifications continues in #30
