### ISSUE TITLE
Tasks are displayed in wrong order

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-app#294]
Some tasks are displayed on couriers app in a different order than on dispatch's dashbord. Some tasks disappear
Eg. : 

<table width="100%">
<tr><td>Dashboard</td><td>App</td></tr>
<tr>
<td valign="top">
<pre>
7804
7805
7806
7802
7803
7776
7777
7774
7775
</pre>
</td>
<td valign="top">
<pre>
7804
7805
7806
7776
7774
7775
</pre>
</td>
</tr>
</table>

**Comment by alexsegura** [comment]
@rayon9coop I never managed to reproduce this issue, did it happen again?

The tasks _should be_ displayed as they are returned by the server, and the server is returning correct order. However there is some code in the app to manage tasks orders, maybe there's a bug in there? Somehow #348 should fix this, or at least it will make sure tasks are displayed in the same order the server returns them.

**Comment by alexsegura** [comment]
Fixed in 3e05f05178d034892f3e9f1aa83d6b4ecb668aa2

**Comment by rayon9coop** [comment]
No, this issue didn't happen again.
