### ISSUE TITLE
Signature screen as default

### ISSUE THREAD

**Issue by CCCC-Jorrit** [coopcycle/coopcycle-app#314]
Instead of the photo screen, for POD. Or are there lots of people in Coop who take photos instead of signatures?

**Comment by CCCC-Jorrit** [comment]
There are some people mainly using photo and others mainly using signature. So would be best to have the person who uses the app decide what is default.

**Comment by PasLoin** [comment]
Maybe this (default) can be configured by "organisation" ; store ; restaurant and after by courrier personal settings.

**Comment by CCCC-Jorrit** [comment]
I think both things are important and different per company. For us it's 99% signatures and therefore I think a default would be good to start with and later maybe defined by what is used most at reoccurring clients
