### ISSUE TITLE
Pull to refresh does not work with an empty day

### ISSUE THREAD

**Issue by GuidoHaagen** [coopcycle/coopcycle-app#324]
When a day has no stops you can not pull to refresh

**Comment by alexsegura** [comment]
Pull-to-refresh would not make sense when the list is empty. 
For this we should do like Twitter.

![téléchargement (1)](https://user-images.githubusercontent.com/1162230/71746745-0d248980-2e6e-11ea-9123-e31a5b9a11b4.png)
