### ISSUE TITLE
Better display on task list

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-app#35]
Improve the task list display : 
 - pickup/dropoff
 - information about task
 - "hot task" (?)

**Comment by alexsegura** [comment]
When a task is completed, it should appear as "disabled": text color should be grey, I mean.

**Comment by couleurmate** [comment]
@Atala Could you develop _hot task_ ? 

You mean it all about managing urgent tasks ?

**Comment by Atala** [comment]
Yes sorry, I was meaning tasks that are urgent, i.e. due in 15 min

**Comment by alexsegura** [comment]
In dabebc45b2f97339e39b825521248c799754cafd, tasks are styled differently depending on status. 

<img width="377" alt="capture d ecran 2018-02-20 a 00 43 59" src="https://user-images.githubusercontent.com/1162230/36401347-4107089c-15d7-11e8-9ff5-d2afeaacae98.png">

**Comment by alexsegura** [comment]
I think this has been improved even more in 4ca60756d28aeef4921e157c71f38a079aa066bf & 4ca60756d28aeef4921e157c71f38a079aa066bf. 

Let's close this one & open more detailed issues, for example for "hot tasks".

<img width="375" alt="capture d ecran 2018-03-01 a 03 22 20" src="https://user-images.githubusercontent.com/1162230/36823903-cccadf5a-1cff-11e8-8fe8-0bb29f4177ea.png">
