### ISSUE TITLE
deliveries don't appear anymore

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-app#401]
I reported this problem on my android phone directly to Mex but now this problem was reported by another messenger which use an iphone.

**Comment by alexsegura** [comment]
When this happens, disconnect and reconnect in the app. 

There are 2 problems:
- the app is not able to renew authentication in some cases, I'm trying to understand why
- the errors are not shown to the user, so the user thinks everything works while authentication is lost

**Comment by alexsegura** [comment]
Closing since this is related to know issues around authentication refresh
