### ISSUE TITLE
Inconsistencies in the Language

### ISSUE THREAD

**Issue by GuidoHaagen** [coopcycle/coopcycle-app#409]
![grafik](https://user-images.githubusercontent.com/56302059/73248662-a156e780-41b3-11ea-89cd-4e55f3534880.png)

The weekday appears in French.

**Comment by damienlapoitavelo** [comment]
![image](https://user-images.githubusercontent.com/43618873/73375019-76f05180-42bb-11ea-99f3-e3ce4d86ad69.png)
I've just discovered than we made a spelling mistake when we had registered the restaurant ( Manhattan ). Since december we have corrected this mistake, but it always present on the app

**Comment by GuidoHaagen** [comment]
Hi Everybody, we need this to fix. At tricargo very few people speak french and they keep messing it up

**Comment by alexsegura** [comment]
Fixed in 65c79b3f7facf2ad982dbd3621128c7ff45bd7f5
