### ISSUE TITLE
restaurant notif in customer account

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-app#486]
I use coopcycle app on my android tab ( galaxy tab 2, android 5.1.1 ) and I used my administrator account. I received commands notification only when it was a "Grand ours restaurant" command. Last days I was connected with my customers account and I received notification when a Grand ours command happened.
Maybe this news can help you : One years ago I connected my tab with Grand ours account to help us ( I know the password ).

**Comment by alexsegura** [comment]
Duplicate of #178
