### ISSUE TITLE
Publish the app on FDroid

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-app#49]
https://f-droid.org/

**Comment by Atala** [comment]
Useless for now on

**Comment by mulles** [comment]
Why is this useless?

**Comment by logos88** [comment]
I don't have Google Play installed. If coopcycle could work without google services and be installed from F-Droid I would surely install it and use it.

**Comment by Porrumentzio** [comment]
It would be greatful being able to use the app on a free way, and so without needing to install it from Google Play for Android

Please, consider adding it to F-Droid
