### ISSUE TITLE
Name field of the person who accepted the delivery

### ISSUE THREAD

**Issue by CCCC-Jorrit** [coopcycle/coopcycle-app#492]
Best with forced to do option. In my opinion this should always be done. Signatures can't be read 99% of the time and you need to be able to tell who signed for the delivery when your client wants to know this.

**Comment by alexsegura** [comment]
Fixed in 8546c77ba946cf0ab0c630d9c3e3cfe32cda2e19

![contact_name](https://user-images.githubusercontent.com/1162230/76982963-eb02b980-693c-11ea-9ff1-d85aea0fa9e5.gif)

**Comment by alexsegura** [comment]
Please note that if the recipient name is _already_ set on a task, it will be pre-filled.
