### ISSUE TITLE
Ability to see 'tips' from customer in the separate in the cart list and also in the notification pop-up on the map.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-app#526]
Being able to see the tip will allow the courier to thanks the customer when he delivers the order.

**Comment by 552020** [comment]
Yes. This would more than nice, I would say almost "important".

**Comment by MathildeS** [comment]
+1

**Comment by ERAMANrepartos** [comment]
How do you deal with tips? How are they distributed? Do we want to show this information, and thereby incentivize the prioritization of one order over another? 

This is very dependent on the structure of the cooperative, and should be taken as part of the large conceptualization of the platform. I'm going to close the issue, but the subject will be in a new issue that will appear soon
