### ISSUE TITLE
Add button to center on current position

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-app#53]

**Comment by alexsegura** [comment]
We are using [MapView](https://github.com/react-community/react-native-maps/blob/master/docs/mapview.md) from [react-native-maps](https://github.com/react-community/react-native-maps)

There is a `showsMyLocationButton`, but it [doesn't work out of the box](https://github.com/react-community/react-native-maps/issues/1033)

**Comment by couleurmate** [comment]
Is it possible to easily set a default ZoomLevel ? It should be a little bit broader and could be nice if it also reset the map to north orientation.
