### ISSUE TITLE
Push-notifications not received for task assigned/unasssinged

### ISSUE THREAD

**Issue by dingusdong** [coopcycle/coopcycle-app#572]
Push-notifcations not received when a task is assigned/unassinged to a courier using an iPhone.

**Comment by dingusdong** [comment]
Also happening on Android

**Comment by alexsegura** [comment]
I think it's because of this piece of code server side

https://github.com/coopcycle/coopcycle-web/blob/2462d21c8ff4e0ba1baa523e446cfc72a61f009f/src/AppBundle/Doctrine/EventSubscriber/TaskSubscriber.php#L156-L160

**Comment by alexsegura** [comment]
Probably fixed in 171a33a0cd25cc6b35943e8471dabb42480a66d0, reopen if it happens again
