### ISSUE TITLE
en: Text horizontal-overflow on RestaurantsPage

### ISSUE THREAD

**Issue by eliasmalik** [coopcycle/coopcycle-app#59]
When no restaurants are found:

![screen shot 2018-03-02 at 15 39 35](https://user-images.githubusercontent.com/12719553/36907304-3ca8e192-1e30-11e8-9f6e-473319c98b27.png)

This is on the iPhone X simulator. Haven't looked into it yet.

**Comment by Paul-Eraman-CoopCycle** [comment]
finished! 🥳
