### ISSUE TITLE
Improve the receipt layout/format of orders.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-app#590]
Something similar to this.

- CoopCycle or the coop logo
- Order number in large font
- Order pickup time in bold
- Order date and time
- Customer first name and last name initial
- Customer note/comment

![image](https://user-images.githubusercontent.com/51931067/81201917-c67ea180-8fbd-11ea-84c0-3f3180e199a2.png)

This is how it looks now. 

![image](https://user-images.githubusercontent.com/51931067/81202044-ee6e0500-8fbd-11ea-9539-4008257d1a9f.png)

**Comment by biologeek** [comment]
Just to say I had a remark from a customer today about this topic. They would like to have at least the name of the customer on the ticket. 
That would make order management much easier for them.

**Comment by ERAMANrepartos** [comment]
I believe this has been updated! 🥳 reopen if not
