### ISSUE TITLE
Toggle open/close comments box to see order items.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-app#593]
Be able to see the order number and when clicking on it it expands open and you can see the order items.

![image](https://user-images.githubusercontent.com/51931067/81203018-4eb17680-8fbf-11ea-9ab7-1c420777fb98.png)

**Comment by ERAMANrepartos** [comment]
How? All the info you request is already there, in which case this would be a UI/UX request. Closing the issue, but we are tackling UI/UX in a more efficient way now.
