### ISSUE TITLE
Show customer name on the restaurant side.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-app#596]
![image](https://user-images.githubusercontent.com/51931067/81210105-4d854700-8fc9-11ea-82d2-c1bf96e67c45.png)

**Comment by MathildeS** [comment]
+1 on this issue, It's asked by the restaurants to have 
- the name and the address when there is a delivery
- the name when it's click and collect

So far, the restaurant can't identify the people supposed to come collect the food when it is not delivered. And when they get a call about the delivery, they need to know which order they are talking about.

**Comment by ERAMANrepartos** [comment]
There are times when we don't want a restaurant talking directly to the client...

I'm going to recreate this issue in a new way that takes into account various use cases. I'm closing this, but expect a new issue in the follow weeks
