### ISSUE TITLE
Show the name couriers on assigned orders and show text if collected.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-app#597]
When an order has been assigned to a courier show the courier name in a second line for each order and when the order has been collected show `collected` next to the courier name. It helps the restaurant to know when an order has been taken care of.

Reflect similar idea from this [issue here](https://github.com/coopcycle/coopcycle-web/issues/1399)

E.g.: 
`RR £16.50 5:01 PM`
`AlexI - assigned`

`RR £16.50 5:01 PM`
`AlexI - collected`

![image](https://user-images.githubusercontent.com/51931067/81210233-81f90300-8fc9-11ea-8f21-ec764d242118.png)

**Comment by ERAMANrepartos** [comment]
We do not want this. Personal information of this type should be carefully protected, and definitely not shared by default. Closing issue unless someone makes a new issue requesting this after a decision as a collective to allow this type of behavior
