### ISSUE TITLE
Use server settings for default map region

### ISSUE THREAD

**Issue by eliascodes** [coopcycle/coopcycle-app#60]
related to #21

https://github.com/coopcycle/coopcycle-app/blob/b50afdf74cd672da7a474e00cae42de38bee32ae/src/page/OrderTrackingPage.js#L16-L23

Ideally it would be configurable

**Comment by alexsegura** [comment]
This should be retrieved from the API, as each instance is centered on a lat/lng.

First, we need to add an endpoint to retrieve settings. 
See coopcycle/coopcycle-web#249

**Comment by alexsegura** [comment]
See #91 

Now we need to return the default coordinates of the instance in the settings endpoint, and store it locally.
