### ISSUE TITLE
react-native link duplicates lines in Android project

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-app#62]
When running `react-native link`, some lines are duplicated in the Android project

```
modified:   android/app/build.gradle
modified:   android/app/src/main/java/fr/coopcycle/MainApplication.java
modified:   android/settings.gradle
```

```
$ git diff android/app/build.gradle
diff --git a/android/app/build.gradle b/android/app/build.gradle
index 3ff21d3..df94611 100644
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@ -152,6 +152,10 @@ android {
 }

 dependencies {
+    compile project(':tipsi-stripe')
+    compile project(':react-native-maps')
+    compile project(':react-native-locale-detector')
+    compile project(':react-native-keep-awake')
     compile project(':react-native-locale-detector')
     compile(project(':react-native-keep-awake')){
       exclude group: 'com.google.android.gms'
```

I think it is due to the Gradle plugin, React Native 0.54 has just been released, will give it a try.

**Comment by Atala** [comment]
I think I know where it comes from, let me have a look.

**Comment by alexsegura** [comment]
It looks like `react-native link` kind of "hangs": when I run the command, I have to hit enter to "finish" it.

**Comment by Atala** [comment]
The [workaround I saw once](https://github.com/react-community/react-native-maps/issues/818#issuecomment-312353768) isn't working.

Good news is there is PR waiting to be merged in react-native, just have to wait for it : facebook/react-native#18131

**Comment by alexsegura** [comment]
Oh ok I thought the bug was only affecting us. 
React Native 0.54 has just been released, let's wait a little more.

**Comment by Atala** [comment]
gr8
