### ISSUE TITLE
Some text input fields ignore user font size preferences

### ISSUE THREAD

**Issue by vincentdcom** [coopcycle/coopcycle-app#635]
**Describe the bug**
Android users can have system wide font size preferences. These are not accounted for some (?) fields in the CC app.

**To Reproduce**
1. Set font size preference to something different (and bigger) than "default"
2. In the app, add some products to an order and go to Cart
3. Click on 'add promo code'
4. Write text in the field

**Expected behavior**
Height of text input fields should accomodate user setting for font size

**Screenshots**
![image](https://user-images.githubusercontent.com/1901398/83323940-30f3cc00-a262-11ea-93d3-d73be2653688.png)
Other example : authentication screen (also note empty "validate" text on button)
![image](https://user-images.githubusercontent.com/1901398/83323975-64cef180-a262-11ea-970b-7ebbe325ff2d.png)

**Smartphone (please complete the following information):**
 - Device: Android Realme5
 - OS: Android 10
 - CC app : 1.0.22

**Comment by ERAMANrepartos** [comment]
Has this been fixed? @alexsegura

**Comment by Paul-Eraman-CoopCycle** [comment]
At the moment we cannot prioritize working with all text sizes and all phone sizes I don't think...
