### ISSUE TITLE
no ring on iphone for restaurant

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-app#639]
**Describe the bug**
3 restaurants which use the app with their iphones doesn't have notifications when commands happen. In their settings notifications for our app is active. But when they've already opened the app during the morning, notifications work. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alexsegura** [comment]
Fixed in 22094ec5f4d1351743e18bda533dc74f3332369b & 171a33a0cd25cc6b35943e8471dabb42480a66d0
