### ISSUE TITLE
Activate/desactivate product not working #restaurant

### ISSUE THREAD

**Issue by TifaineSicklo** [coopcycle/coopcycle-app#640]
**Describe the bug**
Threw the app as a restaurant you desactivate product, it doesn't appear "indispo" on the website andwhen you comme back in your product mangage it activate like you didn't desactivate it or it desactivate other product you don't select before.

**To Reproduce**
1. Go to 'restaurant'
2. Click on 'parameters -> product manage -> desactivate'
3. Go to 'website of the restaurant'
4. See error : some products are not descativate

**Expected behavior**
Work like before :)

**Desktop (please complete the following information):**
I have no idea what i have to complete here :/
It happens on android i don't try on ios

**Smartphone (please complete the following information):**
I have no idea what i have to complete here :/
It happens on android i don't try on ios

**Additional context**

**Comment by alexsegura** [comment]
Fixed in coopcycle/coopcycle-web@11304f28572dc061802e75bd2ef5bab37db31053
