### ISSUE TITLE
UK addresses not found on mobile apps "This address is not precise enough"

### ISSUE THREAD

**Issue by georgeowell** [coopcycle/coopcycle-app#669]
**Describe the bug**

Similar to now solved https://github.com/coopcycle/coopcycle-web/issues/1288

When we search for you UK addresses in the mobile app, it's really difficult to get the address recognised. Error is`This address is not precise enough`

It'd be great if this was fixed in the mobile app. It was solved in the web app and is working as expected there. Hopefully it isn't too difficult to add that solution for the native apps as well

**To Reproduce**
1. Search for UK address

**Expected behavior**
Similar to web app, postcode is entered and then street number. Valid address is accepted.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Various
 - OS: [e.g. iOS8.1] Android and iOS
 - Browser [e.g. stock browser, safari] Native mobile app

**Additional context**
See other issue: https://github.com/coopcycle/coopcycle-web/issues/1288

**Comment by alexsegura** [comment]
Yes, we need to port what was done on the web to the app

**Comment by georgeowell** [comment]
Just for extra context, we can't really recommend the app to our customers yet due to this. It'd be too frustrating for them. We're currently only recommanding the web app.
