### ISSUE TITLE
App close when I try to add courriers

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-app#670]
On dispatch mode, I try to add courriers and app close suddently

Reproduced on Ios and Androïd (1.0.22)
1. open the app  
2. Click on 'Dispatch'
3. Click on 'Assigned tasks"
4. Click on 'New user'
5. Select a courriers

**Comment by alexsegura** [comment]
Fixed in cfbf93ba93612b5f82798a94117befc02aa818a7

**Comment by alexsegura** [comment]
@rayon9coop as a workaround, you can still swipe one task, and assign the messenger from there
