### ISSUE TITLE
allow users to (automatically) connect to restaurants nearby

### ISSUE THREAD

**Issue by gminorcoles** [coopcycle/coopcycle-app#692]
**In order to**  `achieve something`
When users install the app, the list of restaurants is in the Berlin area. It is confusing for someone in another part of the world. The users needs to know the url of the server that is nearby. However when I tried to type in my server's url, the app could not connect to it. 

**As a** `role`
customer

**I want** `something to be added or changed`
I suggest an automatic discovery by the app of a server nearby. Perhaps a text file with a list of server urls and lat / long could be located at some well-known location, even in the bundled installation of the app ? 

**Whereas currently** `this happens`
I select "choose a city" - my city is not in the list - I hit the ... icon top right, and enter the url of my server - it says nework request failed. It takes many clicks to get to this point, and is not obvious to the tester I am working with.

I am not sure I should try to roll this out to restaurants in my area if the user cannot easily find the restaurants nearby on my server.

**Comment by gminorcoles** [comment]
Thinking about this a bit, I realize that perhaps you could use DNS LOC records, since that feature of DNS seems to fit the purpose quite well.

**Comment by gminorcoles** [comment]
but a text (hosts) file is simpler

**Comment by vladimir-8** [comment]
Related to https://github.com/coopcycle/coopcycle-app/issues/817
