### ISSUE TITLE
Implement Mercado Pago for Latam

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-app#729]
The lib [react-native-mercadopago-px](https://github.com/BlackBoxVision/react-native-mercadopago-px) seems pretty good, and actively maintained. 

On server-side, it would need to implement the "preferences" API (as described in the docs)

Also, watch BlackBoxVision/react-native-mercadopago-px#14 to implement Marketplace flow.

**Comment by sgobotta** [comment]
I've done a little research and this could be a list of tasks that have to be done:

+ Implement new methods in `actions.js` (refactor the `checkout` function) to decide whether to use stripe or mercadopago. That has to do with the region of the server, right? It would be useful to know how the app client knows the server's `COUNTRY`.
+ Set preferences from the server. Is there any existent API that stripe uses so can re-use it? Or do we have to implement a new one? Seems to me, everything can be obtained from the existent cart from the db (quantity, item title, description, currency, item), so no additional params need to be be sent from the app client.

Any other ideas?

**Comment by alexsegura** [comment]
> It would be useful to know how the app client knows the server's COUNTRY

The app retrieves some settings from the server when connecting to an instance. Among those settings, there is the country. 
Take a look at the [tests of the settings endpoint](https://github.com/coopcycle/coopcycle-web/blob/7e292d0597693da179767d57eaf68e4c3e18f8c0/features/settings.feature). IMHO, it would be better to return a new key on this endpoint, let's say `payment_gateway`, using the [GatewayResolver](https://github.com/coopcycle/coopcycle-web/blob/7e292d0597693da179767d57eaf68e4c3e18f8c0/src/Payment/GatewayResolver.php) class. This way, we don't need to duplicate the logic on the app. Also of course, this endpoint needs to return the Mercado Pago publishable key. 

> Set preferences from the server. Is there any existent API that stripe uses so can re-use it? Or do we have to implement a new one?

No, with Stripe we just generate a token on the app, and send it to the server, via [`/api/orders/{id}/pay`](https://github.com/coopcycle/coopcycle-web/blob/7e292d0597693da179767d57eaf68e4c3e18f8c0/src/Action/Order/Pay.php)

As you are suggesting, everything can be done server-side to generate the Mercado Pago Preference. 
So either we create a new endpoint, like `GET /api/orders/{id}/mercado-pago-preference`, or we add a new property to the order payload, like `mercadopagoPreferenceId`, which is calculated each time the order is updated (see [OrderPaymentProcessor](https://github.com/coopcycle/coopcycle-web/blob/master/src/Sylius/OrderProcessing/OrderPaymentProcessor.php) which could be adapted for this)

The app would still need to call the `/api/orders/{id}/pay` endpoint after payment succeeded, so that we store in database the [return value](https://github.com/BlackBoxVision/react-native-mercadopago-px#return-value) of the payment flow.
