### ISSUE TITLE
delivery status : icon inside marker 

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-app#73]
It could be nice to easily see task's status directly on marker. It could be done by changing marker's color but it could conflict with tag's color. A trick would be to display an icon inside the marker : 
todo : `empty` or `tag's numeral value` 
done : :heavy_check_mark: 
failed : :x:
 
![screenshot_20180228-172210](https://user-images.githubusercontent.com/13315760/37592155-26d43664-2b6e-11e8-84c3-3c27e3479293.png)

**Comment by Atala** [comment]
On dashboard
<img width="1273" alt="capture d ecran 2018-03-22 a 14 30 39" src="https://user-images.githubusercontent.com/4426585/37773367-b6ec266e-2ddd-11e8-951f-cab1c8e187f4.png">

**Comment by alexsegura** [comment]
Fixed in #319
