### ISSUE TITLE
In order to spend less time searching while doing dispo I would favour having all drivers in an alphabetical order

### ISSUE THREAD

**Issue by GuidoHaagen** [coopcycle/coopcycle-app#738]
**In order to**  have it easier to find the drivers in the app

**As a** dispatcher preparing the goods for the drivers I check what goods they`ll deliver

**I want** the drivers to be in alphabetical order (like on the web)

**Whereas currently** I am scrolling and searching. That takes up time, especially if there are a lot of drivers

**Comment by vladimir-8** [comment]
Linked to https://github.com/coopcycle/coopcycle-web/issues/1691
