### ISSUE TITLE
Logout crash immediatly 

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-app#81]

**Comment by alexsegura** [comment]
This only affects Android.

See facebook/react-native#18696

<img width="319" alt="capture d ecran 2018-04-12 a 18 17 54" src="https://user-images.githubusercontent.com/1162230/38690240-eb3259d8-3e7d-11e8-8b17-c2cf1683e35a.png">

**Comment by alexsegura** [comment]
We need to wait for React Native 0.55.3

**Comment by alexsegura** [comment]
Fixed in 1e3299b47484a64e8cac9f93de723ddf81d94041
