### ISSUE TITLE
Marker clustering

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-app#84]
When several markers with close enough geolocs, it should be possible to collapse those tasks on the map. Use case = same pickup for different dropoff or several dropoffs in same building
Option 1 : filtering 
Option 2 : clustering

**Comment by couleurmate** [comment]
https://github.com/Leaflet/Leaflet.markercluster

**Comment by alexsegura** [comment]
- react-community/react-native-maps#213
- https://github.com/novalabio/react-native-maps-super-cluster
- https://github.com/venits/react-native-map-clustering
