### ISSUE TITLE
CoopCycle PT needs some help

### ISSUE THREAD

**Issue by jfoclpf** [coopcycle/coopcycle-app#882]
Hi there, I'm writing from COOBI, the CoopCycle organisation from Lisbon, PT.
We really want to use your APP

I was trying to implement the project in my machine and I followed your instructions. 

Our project ID is `coopcycle.app.pt`

- I installed all the necessary SW and packages
- I setup a firebase account and downloaded the file into `android/app/google-services.json`, 
- I configured Google Maps API and created a file `android/app/gradle.properties` with the `googleMapsApiKey=A....`

Then when I ran `npm run android` I got this error
```
* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'fr.coopcycle'
```

I replaced `fr.coopcycle` by our `coopcycle.app.pt` in the files `android/app/build.gradle` and `android/app/src/main/AndroidManifest.xml`. Is that ok? 

Then I replaced `google-services.json.dist` by our `google-services.json`. Is that OK?

Now when I run `npm run android` I got this error

```
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> java.lang.NullPointerException (no error message)
```

What am I doing wrong?
Thanks

**Comment by vladimir-8** [comment]
Hi @jfoclpf I remember I had a similar error, and if I remember correctly it was due to the missing `googleMapsApiKey`. I see that you've added gradle.properties file already, but are you sure that gradle looks it in this path as `android/app/gradle.properties`? There is some information on the default config for it in this docs https://github.com/coopcycle/coopcycle-app#geta-google-maps-api-key

**Comment by jfoclpf** [comment]
Thank you very much. In the meantime I spoke directly with @alexsegura and everything was clarified

**Comment by jfoclpf** [comment]
> Thank you very much. In the meantime I spoke directly with @alexsegura and everything was clarified 

You may close this issue therefore
