### ISSUE TITLE
Impossible finish a drop off task

### ISSUE THREAD

**Issue by TifaineSicklo** [coopcycle/coopcycle-app#902]
The courrier "start" the task (drop off) by mistake and change it by "complete" to finish it. But a message error appear (on courrier side and dispatch side, we try both). 
![04e6123a-dc84-4098-a30a-c809ad9ae1e6](https://user-images.githubusercontent.com/59088580/102332595-94d6ab80-3f8c-11eb-9bb4-5a7601de5a56.jpg)

**Comment by alexsegura** [comment]
It is a server related error, closing
