### ISSUE TITLE
Store orders created in the app do not respect "zones", are not visible in "Orders" and do not send "Emails".

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-app#903]
**Describe the bug**
Orders placed by a Store owner 
- [x] do not respect limit set by a Zone (geojson) or radius (km) 
- [x] are not visible in the Orders section
- [x] do not send a notification email

**To Reproduce**
1. Login the app with a user account that is assigned to a Store.
2. Select the Store in the app.
3. Click the plus button to create an order.
4. Input an address which is outside the zone or radius.
5. You'll get no error message.
6. After the order is created check the Orders section as admin.
7. The recently created orders doesn't show in the Orders section.

**Expected behavior**
Orders created as a Store owner in the app should not be allowed to be created if the address goes beyond the set limit and they should show in the Orders section and should send a notification email of a new order.

**Comment by Paul-Eraman-CoopCycle** [comment]
we fixed the zone issue with a limiting feature in their settings page, closing
