### ISSUE TITLE
Time and date of the order to appear on the app in restaurant backend

### ISSUE THREAD

**Issue by ChloeOLVO** [coopcycle/coopcycle-app#944]
Currently restaurants do not see time and date of the order when they receive a new order on their backend app.
They wich to have at least the information of time and date of the order. Very often they just use the app to handle food production. Not knowing time and date is a problem for them.

**Comment by biologeek** [comment]
Hi @ChloeOLVO ,
some of our restaurants also experience issues with time and date. For instance some customers order for next days and the restaurant assumes they are for today as it shows no date or day

Do you refer to these parts ?
![image](https://user-images.githubusercontent.com/11749973/108024447-e4853200-7024-11eb-8ef1-7686c6d0bcb6.png)

![image](https://user-images.githubusercontent.com/11749973/108024624-362dbc80-7025-11eb-8da3-cd9204ae4964.png)

**Comment by biologeek** [comment]
We experienced several use cases issues with date and time for restaurants that lead to order cancellations from restaurant that did not get the good information. 

Let me explain : 

- Customer orders for next day at 20:00
- Restaurant is notified. First confusing thing is that the order appears on today's list of orders while it is not for today (see picture 1 above). Second issue seems about the timezone. See all pictures, order is to be prepared between 18:40 and 18:50. For the restaurant it appears 1 hour before which leads to errors at preparation.
- Next when restaurant clicks to see the order, information is still wrong and confusing cause he still does not have the day of preparation and still has the wrong time 

Current workaround we gave to restaurant is to reload order list and eventually to check their emails to be sure the order is for today but that's being really mind confusing for them when people order at the same time for different dates. 

Could you give an eye on this @alexsegura. If it's just about modifying templates with variables, I may help on it.

**Comment by alexsegura** [comment]
Related issue #192

**Comment by alexsegura** [comment]
The real issue coopcycle/coopcycle-web#2134

**Comment by ChloeOLVO** [comment]
Hi @biologeek , the issue (and I'm expecting restaurants to send me screenshots of the app) is that when they receive an order:
1/ Unless they approve the order - they don't have time and date information of the order on the app
2/ The email they receive when an order is passed by the client doesnt have time and date either
3/ When the approve the order on the app, they have to scroll each day on the calender to find the order if the order is not on the D-Day.

Do you experience the same issue?

**Comment by ChloeOLVO** [comment]
@alexsegura I'm not sure we are talking about the same topic right? (I don't really get the purpose of the related issue you sent - maybe too technical for me!)

**Comment by ChloeOLVO** [comment]
![image](https://user-images.githubusercontent.com/74653993/109189118-f177f300-7793-11eb-9478-99bd99f37fd4.png)
The email they receive - if it's possible to put the date of the order on it :)

**Comment by ChloeOLVO** [comment]
![image](https://user-images.githubusercontent.com/74653993/109189224-14a2a280-7794-11eb-8a71-657989d54976.png)
Same as for the email, having the day of preparation of the order would be a great feature for restaurant ! Thanks!

**Comment by ChloeOLVO** [comment]
So yes @biologeek it's basically the same issue :)

**Comment by ChloeOLVO** [comment]
To sum-up the need for this issue:

Restaurant should have access to the following informations before "approving" the order:
- Date of preparation of the order
- Time of the preparation of the order

Those information should be displaied in the confirmation email, on the back-office website and on the app. @alexsegura (do you need a more detailed feature request or is it ok? :) )

![image](https://user-images.githubusercontent.com/74653993/110308955-0b6dcd00-8001-11eb-89ab-cada1539a8bf.png)

![image](https://user-images.githubusercontent.com/74653993/110308964-10328100-8001-11eb-9669-6c38d9d10130.png)

**Comment by ERAMANrepartos** [comment]
This is a key issue and this has not been significantly updated. Putting on the roadmap

**Comment by ERAMANrepartos** [comment]
Same as #3618 in coopcycle-web

**Comment by Paul-Eraman-CoopCycle** [comment]
We believe this was solved a while back, closing until reported again
