### ISSUE TITLE
As a customer, it is hard to see the restaurants that are open today/tonight in the list (restaurants are not ordered by next opening time)

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-app#946]
In the app (I don't know if there is the same problem on web) from the restaurants list : it is very hard to know the restaurant that are open to order right away, because all the badges are same colour + the restaurants are not ordered (1) opened first (2) opened later.

So you have to browse the whole list to know which are open tonight + you can do mistakes, ordering for a restaurant that are open a few days later.

I would suggest :
 - change dates badge colors between open/open soon/open in a few days
 - order available restaurants first in the list

**Comment by alexsegura** [comment]
Actually badges with next time slot used to be orange/green depending on the time diff, but we changed to "neutral" color (96734f9404e603bb2e4aaaa383dc3fba900674e4) because it was discouraging people to order, the orange color was sending a "bad" signal.

**Comment by Atala** [comment]
Green and light green may be better ?

I think what is important is that you can see the difference when there are restaurants for tonight AND restaurants for tomorrow lunch (you usually want to eat now not tomorrow). Maybe a little bit more logic to add.
