### ISSUE TITLE
Ask for location permission

### ISSUE THREAD

**Issue by ccoreilly** [coopcycle/coopcycle-app#96]
Currently the app does not ask for permission to access location which make the "My Tasks" page return an error.

The app should check for permissions and request them if not granted.

**Comment by alexsegura** [comment]
Yes, this will be fixed in #92

**Comment by alexsegura** [comment]
#92 has been merged 🚀

![img_4272](https://user-images.githubusercontent.com/1162230/40843211-88e959d4-65b0-11e8-9bff-95fd5d4de321.PNG)
![img_4273](https://user-images.githubusercontent.com/1162230/40843215-8b581016-65b0-11e8-85bc-aac6b4aa322d.PNG)
