### ISSUE TITLE
In order to improve orders acceptation as a restaurant I want real button instead of slide-action

### ISSUE THREAD

**Issue by veloconnect25** [coopcycle/coopcycle-app#964]
As a restaurant I have difficulty accepting orders on the APP. The ergonomics of the slide-button are not good. Often I get it wrong and reject the order by mistake. I am therefore obliged to call customers (when they have entered their number, which is not systematic ...) to apologize and ask to re-order. 

Is it possible to design blue and red "accept" and "reject" buttons for the APP like on the website?

**Comment by mcorreggiari** [comment]
I underline this issue. We have problem with new restaurants to understand slide-button, or when there is people that start work in the restaurant. Moreover restaurants workers are saying that sometimes forget to accept, because they don't see the button.

**Comment by ERAMANrepartos** [comment]
I agree that this would be a big improvement, let me ask how hard it will be

**Comment by Paul-Eraman-CoopCycle** [comment]
Not planned
