### ISSUE TITLE
Display order's number in tasks lines

### ISSUE THREAD

**Issue by veloconnect25** [coopcycle/coopcycle-app#989]
Restaurant owners often ask for order numbers to couriers.

1- Couriers ask to have it directly in their to-do list, without having to click on it.

2 - As a dispatcher, it is sometimes useful to re-check the contents of the orders to estimate their weight / volume and to decide whether they can be given together to the same courier. The fact that the order numbers do not appear on the administration panel makes things a bit complicated.

I think it would be useful to display the restaurant order numbers next to the task numbers.

**Comment by ERAMANrepartos** [comment]
This is now visible both in the app as a rider and in the admin dashboard
![image](https://user-images.githubusercontent.com/77277854/235224941-dd4efca7-6aaf-4816-aa07-e767c9372948.png)
![image](https://user-images.githubusercontent.com/77277854/235224962-06ca6322-0945-4fce-b0f7-de917f37df69.png)


However, I do not see any reason why the task number should be in either of these locations, given its technical use. I will make a new issue to remove that.
