### ISSUE TITLE
Images not displayed on iOS 14

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-app#990]
facebook/react-native#29279

![Simulator Screen Shot - iPhone 11 - 2021-03-12 at 22 58 08](https://user-images.githubusercontent.com/1162230/111002889-7b27e300-8386-11eb-9c75-9575e20f3f7e.png)

**Comment by udaysagartammina** [comment]
Hi @alexsegura did you find the any solution? please share me I'm stuck with this issue.

**Comment by alexsegura** [comment]
No @udaysagartammina, I just noticed this when trying a new Macbook with Apple Silicon running XCode 12 and iOS 14 😕
I opened the issue to not forget, but I have not investigated further.
