### ISSUE TITLE
Calender does not display on the tablet

### ISSUE THREAD

**Issue by ColineKpenou** [coopcycle/coopcycle-app#992]
The calendar doesn't display well on the app on a tablet, the restaurant can't chose the right date. 

See picture attached

![Capture](https://user-images.githubusercontent.com/79150125/111336335-6e044000-8675-11eb-88de-f92076a33930.JPG)

**Comment by alexsegura** [comment]
@ColineKpenou I need more details, like the Android version, etc...

**Comment by ERAMANrepartos** [comment]
Closing due to lack of information. But interface issues are on the roadmap...
